//===-- NumpyOps.td - Numpy dialect bind -------------------*- tablegen -*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

#ifndef NPCOMP_PYTHON_DIALECTS_NUMPY_BIND
#define NPCOMP_PYTHON_DIALECTS_NUMPY_BIND

include "mlir/Bindings/Python/Attributes.td"
include "npcomp/Dialect/Numpy/IR/NumpyOps.td"

#endif
