//===-- TorchBind.td - Torch dialect bind ------------------*- tablegen -*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

#ifndef NPCOMP_PYTHON_DIALECTS_TORCH_BIND
#define NPCOMP_PYTHON_DIALECTS_TORCH_BIND

include "mlir/Bindings/Python/Attributes.td"
include "torch-mlir/Dialect/Torch/IR/TorchOps.td"

#endif
