# Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
# Also available under a BSD-style license. See LICENSE.

# This file describes the sets of tests expected to fail for each config.
# This information is deliberately kept in a side table, rather than
# in-situ on the test, as a deliberate layering decision: tests should
# have unique keys to identify them and enable side tables of various kinds
# (this includes down into lower parts of the stack, where a side table
# might be used to keep more elaborate sets of testing configurations).

from torch_mlir_e2e_test.test_suite import COMMON_TORCH_MLIR_LOWERING_XFAILS
from torch_mlir._version import torch_version_for_comparison, version

print(f"TORCH_VERSION_FOR_COMPARISON =", torch_version_for_comparison())

LINALG_XFAIL_SET = COMMON_TORCH_MLIR_LOWERING_XFAILS | {
    # Lowering Torch Backend IR -> Linalg-on-Tensors Backend IR failed
    # 'linalg.depthwise_conv_2d_nchw_chw' op inferred input/output operand #1 has shape's dimension #0 to be 4, but found 8
    "Conv2dWithPaddingDilationStrideStaticModule_depthwise_multiplier",
    "IscloseStaticModule_basic",
    "IscloseStaticModuleTrue_basic"
}

TORCHDYNAMO_XFAIL_SET = {
    #### General TorchDynamo/PyTorch errors

    # torch._dynamo.exc.Unsupported: Tensor.item
    "CumsumModule_basic",

    # TypeError: new_empty(): argument 'size' (position 1) must be tuple of ints, but found element of type NoneType at pos 0
    # RuntimeError: Failed running call_function aten.convolution_backward(...
    # https://github.com/pytorch/pytorch/issues/89629
    "ConvolutionBackwardModule2DPadded_basic",
    "ConvolutionBackwardModule2D_basic",

    # Size result mismatch (exposed by downstream canonicalizer
    # on incompatabile casts).
    # https://github.com/pytorch/pytorch/issues/119407
    "ConvolutionBackwardModule2DStrided_basic",

    # RuntimeError: Index tensor must have the same number of dimensions as self tensor
    # RuntimeError: Failed running call_function aten.nll_loss_backward(...
    # https://github.com/pytorch/pytorch/issues/89630
    "NllLossModuleBackward1DMeanWeight_basic",
    "NllLossModuleBackward1DMean_basic",
    "NllLossModuleBackward1DSumWeight_basic",
    "NllLossModuleBackward1DSum_basic",
    "NllLossModuleBackward1DWeight_basic",
    "NllLossModuleBackward1D_basic",
    # TypeError: uniform() missing 2 required keyword-only arguments: 'dtype' and 'device'
    # RuntimeError: Failed running call_function aten.uniform(...
    # https://github.com/pytorch/torchdynamo/issues/1954
    "UniformNoCorrelationModule_basic",

    #### Torch-MLIR internal compiler errors

    # These are probably due to slightly different ops being recorded by
    # torchdynamo vs. torchscript.

    # No upstream decompositions.
    # %6:4 = torch.operator "aten._embedding_bag_forward_only"(%1, %3, %5, %false, %int0, %false, %none, %false, %int-1) : (!torch.tensor<*,f32>, !torch.tensor<*,si64>, !torch.tensor<*,si64>, !torch.bool, !torch.int, !torch.bool, !torch.none, !torch.bool, !torch.int) -> (!torch.tensor, !torch.tensor, !torch.tensor, !torch.tensor)
    # See also: https://github.com/pytorch/torchdynamo/issues/327
    "AtenEmbeddingBagSumExample_basic",

    # error: unsupported by backend contract: tensor with unknown rank
    # note: see current operation: %1 = "torch.tensor_static_info_cast"(%arg0) : (!torch.vtensor<[5,4,3,2,1],f32>) -> !torch.vtensor<*,f32>
    "ElementwisePreluModule_basic",

    #ERROR: value (Tensor with shape=[2, 3, 6, 10], dtype=torch.float32, min=-1.336e-32, max=+0.9152, mean=+0.4837) is not close to golden value (Tensor with shape=[2, 3, 6, 10], dtype=torch.float32, min=+0.02233, max=+0.9152, mean=+0.4777)
    "UpSampleNearest2dDynamicFactor_basic",
    "ReduceMaxAlongDimUnsignedInt_basic",
    "ReduceMinAlongDimUnsignedInt_basic",
    #ERROR: value (-56) is not equal to golden value (200)
    "AtenIntTensorByteDtypeModule_basic",
    # ERROR: assert isinstance(e, FakeTensor)
    "ElementwiseAddScalar_NumToTensorFloat_Module_basic",
    # ERROR: assert isinstance(e, FakeTensor)
    "RsubInt0d_NumToTensor_Module_basic",

    # ERROR: RuntimeError: Found a custom (non-ATen) operator that either mutates or its inputs: prims::squeeze.. Getting these operators to work with functionalization requires some extra work. For mutable ops you need to register a corresponding out-of-place variant of the op, and you also need to register a Functionalization kernel that performs some boilerplate, telling functionalization to map from the mutable op to the out-of-place op. See a more complete example of how to do this at https://gist.github.com/bdhirsh/7dadbf6296f8f7d1abcf4c482f438aaa.
    "PrimsSqueezeModule_basic",
    "PrimsSqueezeEmptyDimensionsModule_basic",
    "SplitDimStaticModule_basic",
    "SplitDimDynamicModule_basic",

    # ERROR: RuntimeError: Found a custom (non-ATen) operator that either mutates or its inputs: prims::view_of.. Getting these operators to work with functionalization requires some extra work. For mutable ops you need to register a corresponding out-of-place variant of the op, and you also need to register a Functionalization kernel that performs some boilerplate, telling functionalization to map from the mutable op to the out-of-place op. See a more complete example of how to do this at https://gist.github.com/bdhirsh/7dadbf6296f8f7d1abcf4c482f438aaa.
    "PrimsViewOfModule_basic",
    "PrimsViewOfZeroRankModule_basic",

    # See https://github.com/llvm/torch-mlir/pull/2040 and corresponding upstream issue
    # https://github.com/pytorch/pytorch/issues/99752.
    # torch._dynamo.exc.Unsupported: call_function BuiltinVariable(bool) [TensorVariable()] {}
    'TensorToBoolZeroRank_basic',
    'TensorToBool_basic',

    # START tests failing due to: torch._dynamo.exc.Unsupported: call_function BuiltinVariable(float) [TensorVariable()] {}
    'AtenSubFloatModule_basic',
    'AtenMulFloatModule_basic',
    'BoolFloatFalseModule_basic',
    'BoolFloatTrueModule_basic',
    'CeilFloatModule_basic',
    'DivFloatModule_basic',
    'GeFloatIntModule_basic',
    'GeFloatModule_basic',
    'GtFloatIntModule_basic',
    'NeFloatIntModule_basic',
    'SubFloatModule_basic',
    'MulFloatModule_basic',
    'TensorToFloatZeroRank_basic',
    'TensorToFloat_basic',
    # END tests failing due to: torch._dynamo.exc.Unsupported: call_function BuiltinVariable(float) [TensorVariable()] {}


    # START tests failing due to: torch._dynamo.exc.Unsupported: call_function BuiltinVariable(int) [TensorVariable()] {}
    'AddIntModule_basic',
    'AtenIntTensorCharDtypeModule_basic',
    'BoolIntFalseModule_basic',
    'BoolIntTrueModule_basic',
    'DivIntModule_basic',
    'EqIntModule_basic',
    'GeIntModule_basic',
    'GtIntModule_basic',
    'MulIntModule_basic',
    'NeIntModule_basic',
    'SqrtIntModule_basic',
    'SubIntModule_basic',
    'TensorToIntZeroRank_basic',
    'TensorToInt_basic',
    'UnsafeViewCollapseDynamicWithAtenSizeIntModule_basic',
    'ViewCollapseDynamicWithAtenSizeIntModule_basic',
    # END tests failing due to: torch._dynamo.exc.Unsupported: call_function BuiltinVariable(int) [TensorVariable()] {}

    # ERROR: torch._dynamo.exc.Unsupported: Tensor.item
    'AtenItemIntOpModule_basic',
    'AtenItemFpOpModule_basic',

    # ERROR: torch._dynamo.exc.Unsupported: call_method ListVariable() sort [] {'reverse': ConstantVariable(bool)}
    'SortIntListReverse_basic',

    # ERROR: torch._dynamo.exc.Unsupported: call_method ListVariable() sort [] {}
    'SortIntList_basic',

    # START tests failing due to: torch._dynamo.exc.Unsupported: data dependent operator: aten._local_scalar_dense.default
    'AtenFloatScalarModule_basic',
    'AtenIntBoolOpModule_basic',
    'QuantizedMLP_basic',
    'ScalarImplicitFloatModule_basic',
    'ScalarImplicitIntModule_basic',
    # END tests failing due to: torch._dynamo.exc.Unsupported: data dependent operator: aten._local_scalar_dense.default

    # START tests failing due to: torch._dynamo.exc.Unsupported: dynamic shape operator: aten.bincount.default
    'BincountMinlengthModule_basic',
    'BincountModule_basic',
    'BincountStaticSizeModule_basic',
    # END tests failing due to: torch._dynamo.exc.Unsupported: dynamic shape operator: aten.bincount.default

    # ERROR: torch._dynamo.exc.Unsupported: torch.* op returned non-Tensor bool call_function aten.Bool
    'BoolFloatConstantModule_basic',
    'BoolIntConstantModule_basic',

    # ERROR: torch._dynamo.exc.Unsupported: torch.* op returned non-Tensor int call_function aten.size
    "ViewSizeFromOtherTensor_basic",

    # ERROR: torch._dynamo.exc.Unsupported: torch.* op returned non-Tensor bool call_function aten.__contains__
    'ContainsIntList_False',
    'ContainsIntList_True',

    # ERROR: torch._dynamo.exc.Unsupported: torch.* op returned non-Tensor bool call_function aten.all
    'AllBoolFalseModule_basic',
    'AllBoolTrueModule_basic',

    # ERROR: torch._dynamo.exc.Unsupported: torch.* op returned non-Tensor bool call_function aten.any
    'AnyBoolFalseModule_basic',
    'AnyBoolTrueModule_basic',

    # ERROR: torch._dynamo.exc.Unsupported: torch.* op returned non-Tensor float call_function aten.sqrt
    'SqrtIntConstantModule_basic',

    # ERROR: torch._dynamo.exc.Unsupported: torch.* op returned non-Tensor int call_function aten.size
    'BroadcastDynamicDimModule_basic',

    # START tests failing due to: torch._dynamo.exc.Unsupported: torch.* op returned non-Tensor int call_function aten.Int
    'AtenIntBoolOpConstFalseModule_basic',
    'AtenIntBoolOpConstTrueModule_basic',
    'IntFloatModule_basic',
    'PowIntFloatModule_basic',
    # END tests failing due to: torch._dynamo.exc.Unsupported: torch.* op returned non-Tensor int call_function aten.Int

    # ERROR: torch._dynamo.exc.Unsupported: torch.* op returned non-Tensor int call_function aten.len
    'LenStrModule_basic',

    # ERROR: torch._dynamo.exc.Unsupported: torch.* op returned non-Tensor int call_function aten.numel
    'NumelModule_basic',
    'NumelZeroRankModule_basic',

    # ERROR: torch._dynamo.exc.Unsupported: torch.* op returned non-Tensor int call_function prim.max
    'PrimMaxIntModule_basic',

    # ERROR: torch._dynamo.exc.Unsupported: torch.* op returned non-Tensor int call_function prim.min
    'PrimMinIntModule_basic',
    'PrimMinIntDynamicModule_basic',

    # START tests failing due to: empty graph in dynamo
    'IsFloatingPointFloat_True',
    'IsFloatingPointInt_False',
    'TorchPrimLoopForLikeModule_basic',
    'TorchPrimLoopWhileLikeModule_basic',
    "ScalarConstantTupleModule_basic",
    # END tests failing due to: empty graph in dynamo

    # ERROR due to: backend never runs because of empty frame
    'ConstantBoolParameterModule_basic',

    # START tests failing due to: 'torch.aten.mul.Tensor' op operand #1 must be Any Torch tensor type, but got '!torch.float'
    "AddCDivModule_basic",
    "ElementwiseMulScalarModule_basic",
    "ElementwiseMulScalarModule_float",
    "NativeGroupNormBackwardModule_basic",
    "UpSampleNearest2dDynamicSize_basic",
    "UpSampleNearest2dStaticFactor_basic",
    "UpSampleNearest2dStaticSize_basic",
    "UpSampleNearest2d_basic",
    # END tests failing due to: 'torch.aten.mul.Tensor' op operand #1 must be Any Torch tensor type, but got '!torch.float'

    # START tests failing due to: 'torch.aten.add.Tensor' op operand #1 must be Any Torch tensor type, but got '!torch.float'
    "AtenInstanceNormModule_basic",
    "BatchNorm1DModule_basic",
    "BatchNorm1DWith2DInputModule_basic",
    "BatchNorm2DModule_basic",
    "BatchNorm3DModule_basic",
    "BatchNorm1DStaticShapeModule_basic",
    "ElementwiseAddScalarFloatModule_basic",
    "ElementwiseAddScalarInt64Module_basic",
    "ElementwiseAddScalarIntModule_basic",
    "MobilenetV3Module_basic",
    "NativeBatchNorm1DModule_basic",
    "NativeBatchNorm2DModule_basic",
    "NativeBatchNorm3DModule_basic",
    "NativeBatchNormNoneWeightModule_basic",
    "NativeGroupNormModule_basic",
    "ResNet18Module_basic",
    "ResNet18StaticModule_basic",
    # END tests failing due to: 'torch.aten.add.Tensor' op operand #1 must be Any Torch tensor type, but got '!torch.float'

    # ERROR: 'torch.aten.add.Tensor' op operand #1 must be Any Torch tensor type, but got '!torch.int'
    "ElementwiseAddScalar_TensorLiteralInt32_Module_basic",
    "HBC_basic",

    # ERROR: 'torch.aten.div.Tensor' op operand #1 must be Any Torch tensor type, but got '!torch.float'
    "ElementwiseDivScalarModule_basic",

    # ERROR: 'torch.aten.div.Tensor' op operand #1 must be Any Torch tensor type, but got '!torch.int'
    "ElementwiseAtenDivIntScalarModule_basic",

    # ERROR: 'torch.aten.mul.Tensor' op operand #1 must be Any Torch tensor type, but got '!torch.int'
    "ElementwiseMulScalarModule_int",

    # ERROR: 'torch.aten.sub.Tensor' op operand #1 must be Any Torch tensor type, but got '!torch.float'
    "ElementwiseSubScalarFloatModule_basic",
    "ElementwiseSubScalarIntModule_basic",

    # ERROR: Exception: Unsupported: missing default value for argument 0 in schema for aten.div.Tensor_mode
    "ElementwiseDivRoundingModeFloorModule_basic",
    "ElementwiseDivRoundingModeTruncModule_basic",
    "AdaptiveAvgPool1dStaticLargerOutput_basic",
    "AdaptiveAvgPool1dGeneralDynamic_basic",

    # ERROR: Exception: Unsupported op: get_attr
    "NumToTensorFloatModule_basic",
    "NumToTensorIntModule_basic",
    "TensorFloatModule_basic",
    "TensorIntModule_basic",

    # ERROR: Exception: Unsupported: missing default value for argument 0 in schema for aten.randn.generator
    "RandnGeneratorF64Module_basic",
    "RandnGeneratorModule_basic",

    # START tests failing due to: complex floating point ops
    # END tests failing due to: complex floating point ops

    # ERROR: Exception: Unsupported: return type List[Tensor] in schema for aten.unbind.int
    "UnbindIntListUnpack_Module_basic",
    "UnbindIntGetItem_Module_basic",

    # ERROR: torch._dynamo.exc.Unsupported: call_function BuiltinVariable(float) [TensorVariable()] {}
    "ScatterValueFloatModule_basic",
    # ERROR: torch._dynamo.exc.Unsupported: call_function BuiltinVariable(int) [TensorVariable()] {}
    "ScatterValueIntModule_basic",

    # AssertionError: Unregistered operation: torch.aten._unsafe_index_put
    "UnsafeIndexPutHackedTwin1DFloatNonAccumulateModule_basic",

    # Lowering Torch Backend IR -> Linalg-on-Tensors Backend IR failed
    # 'linalg.depthwise_conv_2d_nchw_chw' op inferred input/output operand #1 has shape's dimension #0 to be 4, but found 8
    "Conv2dWithPaddingDilationStrideStaticModule_depthwise_multiplier",

    # AssertionError: Unregistered operation: torch.aten._scaled_dot_product_flash_attention_for_cpu
    "ScaledDotProductAttentionDifferentModule_basic",

    # AssertionError: Unregistered operation: torch.aten._embedding_bag_forward_only
    "AtenEmbeddingBagStaticModule_basic",

    # Lowering not present for this case
    "ElementwiseToDtypeI64ToUI8Module_basic",

    # torch._dynamo.exc.TorchRuntimeError: Failed running call_function <built-in method add of type object at 0x7f4f8b05a720>(*(FakeTensor(..., size=(3, 4), dtype=torch.int8), 3, 2), **{}): Tensor with dtype torch.int64 is not the expected dtype of torch.int8!
    "ElementwiseAddScalarInt8Module_basic",

    # ERROR: dtype (torch.int64) is not equal to golden dtype (torch.float32)
    "ThresholdBackward2dMixedModule_basic",

    # ERROR: shape (torch.Size([12])) is not equal to golden shape (torch.Size([3, 4]))
    "ArangeStartOutViewModule_basic",

    # ERROR: 'torch.aten.add.Tensor' op operand #1 must be Any Torch tensor type, but got '!torch.float'
    "GroupNormModule_basic",
    "GroupNormNoWeightAndBiasModule_basic",

    # Dynamo does not support tracing quantized tensors
    "ElementwiseDequantizePerChannelModule_basic",
    "ElementwiseDequantizePerTensorModule_basic",
    "ElementwiseQuantizePerTensorModule_basic",
    "AtenMmQuint8_basic",
    "Conv2dQInt8Module_basic",

    # Dynamo not supporting conv_tbc
    "ConvTbcModule_basic",

    "FloatImplicitModule_basic",
    "IntImplicitModule_basic",
}

TORCHDYNAMO_CRASHING_SET = {
    # No upstream decompositions.
    # %6:4 = torch.operator "aten._embedding_bag_forward_only"(%1, %3, %5, %false, %int0, %false, %none, %false, %int-1) : (!torch.tensor<*,f32>, !torch.tensor<*,si64>, !torch.tensor<*,si64>, !torch.bool, !torch.int, !torch.bool, !torch.none, !torch.bool, !torch.int) -> (!torch.tensor, !torch.tensor, !torch.tensor, !torch.tensor)
    # See also: https://github.com/pytorch/torchdynamo/issues/327
    "Aten_EmbeddingBagExample_basic",
    "FullModuleInt3D_basic",
    "ThresholdBackward1dIntModule_basic",
    "ThresholdBackward2dIntModule_basic",
    "ThresholdBackward3dIntModule_basic",
    # See https://github.com/llvm/torch-mlir/issues/2050
    "ElementwiseCloneChannelsLastMemoryFormatModule_basic",
    "ElementwiseCloneContiguousModule_basic",
    "ElementwiseCloneModule_basic",
    "ExpandAsFloatModule_basic",
    "ExpandAsIntModule_basic",
    "ExpandModule_basic",
    "MoveDimIntModule_basic",
    "MoveDimIntNegativeIndexModule_basic",
    "NarrowVerticalTest2_basic",
    "NarrowVerticalTest_basic",
    "NumpyTRank2Module_basic",
    "NumpyTRankNDynamicModule_basic",
    "NumpyTRankNStaticModule_basic",
    "PermuteModule_basic",
    "PermuteNegativeIndexModule_basic",
    "SelectIntNegativeDimAndIndexStaticModule_basic",
    "TestMultipleTensorAndPrimitiveTypesReturn_basic",
    "TModuleRank2_basic",
    "ToCopyModule_basic",
    "TransposeIntModule_basic",
    "TransposeIntNegDimsModule_basic",
    "IndexPutImpl2DNoneIndexStaticModule_basic",
    "MaxPool3dCeilModeTrueModule_basic",
    "MaxPool3dEmptyStrideStaticModule_basic",
    "MaxPool3dLargeDatadModule_basic",
    "MaxPool3dModuleRandomSimple_basic",
    "MaxPool3dModule_basic",
    "MaxPool3dStaticCeilModeTrueModule_basic",
    "MaxPool3dStaticModule_basic",
}

STABLEHLO_PASS_SET = {
    "AdaptiveAvgPool1dNonUnitOutputSizeStaticModule_basic",
    "AdaptiveAvgPool1dUnitOutputSizeStaticModule_basic",
    "AdaptiveAvgPool2dNonUnitOutputSizeStaticModule_basic",
    "AdaptiveAvgPool2dUnitOutputSizeStaticModule_basic",
    "AddIntModule_basic",
    "AliasModule_basic",
    "AllBoolFalseModule_basic",
    "AllBoolTrueModule_basic",
    "AnyBoolFalseModule_basic",
    "AnyBoolTrueModule_basic",
    "ArangeDtypeFloatModule_basic",
    "ArangeDtypeIntModule_basic",
    "ArangeFalsePinMemoryModule_basic",
    "ArangeFloatModule_basic",
    "ArangeIntModule_basic",
    "ArangeNegativeStartFloatModule_basic",
    "ArangeNegativeStartIntModule_basic",
    "ArangeStartFloatModule_basic",
    "ArangeStartIntModule_basic",
    "ArangeStartNegativeStepFloatModule_basic",
    "ArangeStartNegativeStepIntModule_basic",
    "ArangeStartOutDtypeModule_basic",
    "ArangeStartOutModule_basic",
    "ArangeStartOutViewModule_basic",
    "ArangeStartStepFloatModule_basic",
    "ArangeStartStepIntModule_basic",
    "ArangeZeroElementOutputModule_basic",
    "ArgmaxModule_with_dim",
    "AtenComplex64Module_basic",
    "AtenEyeMModuleCPUDevice_basic",
    "AtenEyeMModuleDefaultDtype_basic",
    "AtenEyeMModuleFalsePinMemory_basic",
    "AtenEyeMModuleFloat2D_basic",
    "AtenEyeMModuleInt2D_basic",
    "AtenEyeModuleCPUDevice_basic",
    "AtenEyeModuleDefaultDtype_basic",
    "AtenEyeModuleFalsePinMemory_basic",
    "AtenEyeModuleFloat2D_basic",
    "AtenEyeModuleInt2D_basic",
    "AtenFloatScalarModule_basic",
    "AtenInstanceNormModule_basic",
    "AtenIntBoolOpConstFalseModule_basic",
    "AtenIntBoolOpConstTrueModule_basic",
    "AtenIntBoolOpModule_basic",
    "AtenIntTensorByteDtypeModule_basic",
    "AtenIntTensorCharDtypeModule_basic",
    "AtenItemFpOpModule_basic",
    "AtenItemIntOpModule_basic",
    "AtenMmFloatTypes_basic",
    "AtenMmIntTypes_basic",
    "AtenRoundIntModule_basic",
    "AtenSubFloatModule_basic",
    "AtenToDeviceModule_basic",
    "AvgPool1dStaticModule_basic",
    "AvgPool2dStaticModule_basic",
    "BaddbmmBroadcast1DInputModule_basic",
    "BaddbmmBroadcast2DInputModule_basic",
    "BaddbmmStaticModule_basic",
    "BoolFloatConstantModule_basic",
    "BoolFloatFalseModule_basic",
    "BoolFloatTrueModule_basic",
    "BoolIntConstantModule_basic",
    "BoolIntFalseModule_basic",
    "BoolIntTrueModule_basic",
    "BoolTensorReturnFalseModule_basic",
    "BoolTensorReturnMixedModule_basic",
    "BoolTensorReturnTrueModule_basic",
    "BroadcastListConstructWithMinusOneModule_basic",
    "BroadcastToSameRankStaticModule_basic",
    "BroadcastZeroRankInputStaticModule_basic",
    "BucketizeTensorStaticFloatModule_basic",
    "BucketizeTensorStaticModule_basic",
    "CeilFloatModule_basic",
    "ChunkListUnpackUneven_Module_basic",
    "ChunkListUnpack_Module_basic",
    "CloneModule_basic",
    "ConstantBoolParameterModule_basic",
    "ContainsIntList_False",
    "ContainsIntList_True",
    "ContiguousModule_basic",
    "Conv2dWithPaddingDilationStrideStaticModule_basic",
    "Conv2dWithPaddingDilationStrideStaticModule_depthwise",
    "Conv2dWithPaddingDilationStrideStaticModule_depthwise_multiplier",
    "Conv2dWithPaddingDilationStrideStaticModule_grouped",
    "Conv2dWithPaddingDilationStrideStaticModule_grouped_multiplier",
    "Convolution2DStaticModule_basic",
    "ConvolutionBackwardModule2DStatic_basic",
    "ConvolutionBackwardModule2DStrided_basic",
    "ConvolutionModule2DTransposeStridedStatic_basic",
    "CosineSimilarityStaticBroadcastModule_basic",
    "CosineSimilarityStaticModule_basic",
    "CumsumInputDtypeInt32Module_basic",
    "CumsumStaticModule_basic",
    "CumsumStaticNegativeDimModule_basic",
    "DetachModule_basic",
    "DivFloatModule_basic",
    "DivIntModule_basic",
    "DropoutEvalFloatModule_basic",
    "DropoutEvalIntModule_basic",
    "DropoutTrainStaticShapeModule_basic",
    "EinsumStaticContractRhsModule_basic",
    "EinsumStaticFourDimensionModule_basic",
    "EinsumStaticModule_basic",
    "ElementwiseAbsFloatModule_basic",
    "ElementwiseAbsIntModule_basic",
    "ElementwiseAddScalar_NumToTensorFloat_Module_basic",
    "ElementwiseAddScalar_TensorLiteralInt32_Module_basic",
    "ElementwiseAtenIsinfOpModule_basic",
    "ElementwiseAtenIsneginfOpModule_basic",
    "ElementwiseAtenIsposinfOpModule_basic",
    "ElementwiseAtenLogicalAndOpPromoteBroadcastStaticShapeModule_basic",
    "ElementwiseAtenLogicalNotOpModule_basic",
    "ElementwiseAtenLogicalNotOpPromoteModule_basic",
    "ElementwiseAtenLogicalOrOpPromoteBroadcastStaticShapeModule_basic",
    "ElementwiseAtenLogicalXorOpPromoteBroadcastStaticShapeModule_basic",
    "ElementwiseAtenWhereSelfModule_basic",
    "ElementwiseBinaryStaticShapeModule_basic",
    "ElementwiseBitwiseAndStaticShapeModule_basic",
    "ElementwiseBitwiseNotInt32Module_basic",
    "ElementwiseBitwiseNotInt64Module_basic",
    "ElementwiseBitwiseOrStaticShapeModule_basic",
    "ElementwiseBitwiseXorStaticShapeModule_basic",
    "ElementwiseCeilModule_basic",
    "ElementwiseClampMaxModule_basic",
    "ElementwiseClampMinModule_basic",
    "ElementwiseClampModule_basic",
    "ElementwiseClampTensorInt8Module_basic",
    "ElementwiseCloneChannelsLastMemoryFormatModule_basic",
    "ElementwiseCloneContiguousModule_basic",
    "ElementwiseCloneModule_basic",
    "ElementwiseCosModule_basic",
    "ElementwiseErfModule_basic",
    "ElementwiseExpModule_basic",
    "ElementwiseFloorIntModule_basic",
    "ElementwiseFloorModule_basic",
    "ElementwiseGeluModule_basic",
    "ElementwiseGeluApproximateTanhModule_basic",
    "ElementwiseLeakyReluStaticModule_basic",
    "ElementwiseLogModule_basic",
    "ElementwiseNanToNumModule_Basic",
    "ElementwiseNeFloatTensorStaticModule_basic",
    "ElementwiseNeIntTensorStaticModule_basic",
    "ElementwiseNegModule_basic",
    "ElementwiseOrTensorStaticShapeModule_basic",
    "ElementwisePowTensorBroadcastStaticModule_basic",
    "ElementwisePowTensorStaticModule_basic",
    "ElementwiseReciprocalModule_basic",
    "ElementwiseReluModule_basic",
    "ElementwiseRsqrtModule_basic",
    "ElementwiseSigmoidModule_basic",
    "ElementwiseSinModule_basic",
    "ElementwiseSqrtModule_basic",
    "ElementwiseToDtypeF32ToI64Module_basic",
    "ElementwiseToDtypeI64ToI8Module_basic",
    "ElementwiseToDtypeIdentityModule_basic",
    "ElementwiseUnaryModule_basic",
    "ElementwiseWhereScalarOtherStaticModule_basic",
    "ElementwiseWhereScalarSelfStaticModule_basic",
    "EmptyLikeMemoryFormatModule_basic",
    "EmptyLikeModule_defaultDtype",
    "EmptyLikeModule_falsePinMemory",
    "EmptyLikeModule_float",
    "EmptyLikeModule_int",
    "EmptyModule_contiguous",
    "EmptyModule_defaultDtype",
    "EmptyModule_falsePinMemory",
    "EmptyModule_float",
    "EmptyModule_int",
    "EmptyStridedModule_basic",
    "EqIntModule_basic",
    "ExpandAsIntModule_basic",
    "Fill_TensorFloat64WithFloat32Static_basic",
    "Fill_TensorFloat64WithFloat32_basic",
    "Fill_TensorFloat64WithFloat64_basic",
    "Fill_TensorFloat64WithInt64Static_basic",
    "Fill_TensorFloat64WithInt64_basic",
    "FlattenRank0Module_basic",
    "FlattenStaticModule_basic",
    "FlipModuleStaticShape_basic",
    "FlipNegativeIndexModule_basic",
    "FullLikeModuleDefaultDtype_basic",
    "FullLikeModuleFalsePinMemory_basic",
    "FullLikeModuleFloat2D_basic",
    "FullLikeModuleFloat3DStatic_basic",
    "FullLikeModuleFloat3D_basic",
    "FullLikeModuleInt2DStatic_basic",
    "FullLikeModuleInt2D_basic",
    "FullLikeModuleInt3D_basic",
    "FullModuleDefaultDtype_basic",
    "FullModuleFalsePinMemory_basic",
    "FullModuleFloat2D_basic",
    "FullModuleFloat3D_basic",
    "FullModuleInt2D_basic",
    "FullModuleInt3D_basic",
    "GatherStaticModule_basic",
    "GeFloatIntModule_basic",
    "GeFloatModule_basic",
    "GeIntModule_basic",
    "GeluBackwardModule_basic",
    "GluStaticModule_basic",
    "GroupNormModule_basic",
    "GroupNormNoWeightAndBiasModule_basic",
    "GtFloatIntModule_basic",
    "GtIntModule_basic",
    "IndexTensorMultiIndexStaticModule_basic",
    "IndexTensorStaticContiguousWithNoneModule_basic",
    "IndexTensorStaticModule_basic",
    "IndexTensorStaticNonContiguousWithNoneModule_basic",
    "IntFloatModule_basic",
    "IsFloatingPointFloat_True",
    "IsFloatingPointInt_False",
    "LayerNormLastDimModule_basic",
    "LayerNormModule_basic",
    "LayerNormNormalizeOverAllDimsModule_basic",
    "LeakyReluBackwardStaticModule_basic",
    "LenStrModule_basic",
    "LiftFreshCopyModule_basic",
    "MaskedFillScalarFloatValueStaticModule_basic",
    "MaskedFillScalarIntValueStaticModule_basic",
    "Matmul4dStatic_basic",
    "Matmul_2d",
    "Matmul_dot",
    "Matmul_matvec",
    "Matmul_vecmat",
    "MaxPool2dStaticModule_basic",
    "MaxPool2dWithIndicesStaticModule_basic",
    "MeanDimAllReduceKeepdimModule_basic",
    "MeanDimAllReduceModule_basic",
    "MeanDimEmptyDimModule_basic",
    "MeanDtypeModule_basic",
    "MeanDynamicSizesModule_basic",
    "MeanModule_basic",
    "Mlp2LayerModuleNoBias_basic",
    "MmDagModule_basic",
    "MmModule_basic",
    "MmModule_chained",
    "MmTanhModule_basic",
    "MoveDimIntModule_basic",
    "MoveDimIntNegativeIndexModule_basic",
    "MulFloatModule_basic",
    "MulIntModule_basic",
    "Mv_basic",
    "NarrowHorizontalTest2_basic",
    "NarrowHorizontalTest_basic",
    "NarrowTensorHorizontalModule_basic",
    "NarrowTensorVerticalModule_basic",
    "NarrowVerticalTest2_basic",
    "NarrowVerticalTest_basic",
    "NativeDropoutEvalFloatModule_basic",
    "NativeDropoutTrainStaticShapeModule_basic",
    "NativeGroupNormModule_basic",
    "NativeLayerNormModule4D_basic",
    "NativeLayerNormModule_basic",
    "NeFloatIntModule_basic",
    "NeIntModule_basic",
    "NewEmptyModuleDefaultDtype_basic",
    "NewEmptyModuleFalsePinMemory_basic",
    "NewEmptyModuleFloat2D_basic",
    "NewEmptyModuleFloat3D_basic",
    "NewEmptyModuleInt2D_basic",
    "NewEmptyModuleInt3D_basic",
    "NewEmptyModuleLayoutIntDtype_basic",
    "NewEmptyModuleNonDefaultFloatDtype_basic",
    "NewEmptyModuleNonDefaultIntDtype_basic",
    "NewEmptyStridedModuleDefaultDtype_basic",
    "NewFullModuleDefaultDtype_basic",
    "NewFullModuleFalsePinMemory_basic",
    "NewFullModuleFloat3DStatic_basic",
    "NewFullModuleFloat3D_basic",
    "NewFullModuleInt2D_basic",
    "NewFullModuleInt3D_basic",
    "NewOnesModuleDefaultDtype_basic",
    "NewOnesModuleFalsePinMemory_basic",
    "NewOnesModuleFloat2D_basic",
    "NewOnesModuleFloat3D_basic",
    "NewOnesModuleInt2D_basic",
    "NewOnesModuleInt3D_basic",
    "NewZerosModuleDefaultDtype_basic",
    "NewZerosModuleFalsePinMemory_basic",
    "NewZerosModuleFloat2D_basic",
    "NewZerosModuleFloat3D_basic",
    "NewZerosModuleInt2D_basic",
    "NewZerosModuleInt3D_basic",
    "NewZerosStaticModuleLayoutStrided_basic",
    "NormalizeModule_basic",
    "NumToTensorFloatModule_basic",
    "NumToTensorIntModule_basic",
    "NumelModule_basic",
    "NumelZeroRankModule_basic",
    "NumpyTRank0Module_basic",
    "NumpyTRank1Module_basic",
    "NumpyTRank2Module_basic",
    "NumpyTRankNDynamicModule_basic",
    "NumpyTRankNStaticModule_basic",
    "OnesLikeModule_defaultDtype",
    "OnesLikeModule_falsePinMemory",
    "OnesLikeModule_float",
    "OnesLikeModule_int",
    "OnesModuleCPUDevice_basic",
    "OnesModuleDefaultDtype_basic",
    "OnesModuleFalsePinMemory_basic",
    "OnesModuleFloat_basic",
    "OnesModuleInt_basic",
    "Permute0RankModule_basic",
    "PermuteModule_basic",
    "PermuteNegativeIndexModule_basic",
    "PowIntFloatModule_basic",
    "PrimMaxIntModule_basic",
    "PrimMinIntDynamicModule_basic",
    "PrimMinIntModule_basic",
    "PrimsConvertElementTypeModule_basic",
    "PrimsSqueezeEmptyDimensionsModule_basic",
    "PrimsSqueezeModule_basic",
    "PrimsViewOfModule_basic",
    "PrimsViewOfZeroRankModule_basic",
    "RandIntDtypeModule_basic",
    "RandIntLowDtypeModule_basic",
    "RandIntLowModule_basic",
    "RandIntModule_basic",
    "RandIntPinMemoryModule_basic",
    "RandModule_basic",
    "ReduceAmaxMultiDim_basic",
    "ReduceAmaxOutOfOrderDim_basic",
    "ReduceAmaxSingleDim_basic",
    "ReduceFrobeniusNormModule_basic",
    "ReduceMaxAllDims_basic",
    "ReduceMaxAlongDimNegative_basic",
    "ReduceMaxAlongDimSignedInt_basic",
    "ReduceMaxAlongDim_basic",
    "ReduceMaxFloatModule_basic",
    "ReduceMaxSignedIntModule_basic",
    "ReduceMaxUnsignedIntModule_basic",
    "ReduceMinFloatModule_basic",
    "ReduceMinSignedIntModule_basic",
    "ReduceMinUnsignedIntModule_basic",
    "ReduceSumDimIntListDtypeFloatModule_basic",
    "ReduceSumDimIntListDtypeIntModule_basic",
    "ReduceSumDimIntListElementTypeBoolModule_basic",
    "ReduceSumDimIntListEmptyDimModule_basic",
    "ReduceSumDimIntListFloatModule_basic",
    "ReduceSumDimIntListIntModule_basic",
    "ReduceSumDimIntListKeepDimNegativeDimStaticModule_basic",
    "ReduceSumDtypeFloatModule_basic",
    "ReduceSumDtypeIntModule_basic",
    "ReduceSumElementTypeBoolModule_basic",
    "ReduceSumFloatModule_basic",
    "ReduceSumSignedIntModule_basic",
    "ReduceSumUnsignedIntModule_basic",
    "RepeatModule_basic",
    "ReshapeAliasCollapseModule_basic",
    "ReshapeAliasExpandModule_basic",
    "ReshapeAsModule_basic",
    "ReshapeExpandModule_basic",
    "ReturnThreeTensorFloat32_basic",
    "ReturnTwoTensorF32I64_basic",
    "RollModule_basic",
    "RsubInt0d_NumToTensor_Module_basic",
    "ScalarConstantTupleModule_basic",
    "ScalarImplicitFloatModule_basic",
    "ScalarImplicitIntModule_basic",
    "ScalarTensorDefaultDtypeModule_basic",
    "ScalarTensorFloat32Module_basic",
    "ScalarTensorInt32Module_basic",
    "ScalarTensorInt64Module_basic",
    "SelectIntNegativeDimAndIndexStaticModule_basic",
    "SelectScattertStaticModule_basic",
    "SliceModule_basic",
    "SliceNegIdxModule_basic",
    "SliceOutOfLowerBoundStartIndexModule_basic",
    "SliceOutOfUpperBoundIndexModule_basic",
    "SliceOutOfUpperBoundIndexStaticModule_basic",
    "SliceScatterModule_basic",
    "SliceScatterNegativeDimModule_basic",
    "SliceScatterNegativeEndModule_basic",
    "SliceScatterStaticModule_basic",
    "SliceScatterStepVariationModule_basic",
    "SliceScatterZeroDimModule_basic",
    "SliceSizeTwoStepModule_basic",
    "SliceStartEqEndModule_basic",
    "SliceStaticModule_basic",
    "SliceWholeTensorModule_basic",
    "SortIntListReverse_basic",
    "SortIntList_basic",
    "SplitTensorGetItem_Module_basic",
    "SplitTensorLastSmallerModule_basic",
    "SplitTensorListUnpackModule_basic",
    "SplitTensorNegativeDimModule_basic",
    "SplitWithSizesListUnpackModule_basic",
    "SqrtIntConstantModule_basic",
    "SqrtIntModule_basic",
    "SqueezeDimModule_identity",
    "SqueezeDimModule_static",
    "SqueezeDimModule_unitDim",
    "SqueezeModule_allUnitDim",
    "SqueezeModule_static",
    "SubFloatModule_basic",
    "SubIntModule_basic",
    "TModuleRank0_basic",
    "TModuleRank1_basic",
    "TModuleRank2_basic",
    "TensorIntModule_basic",
    "TensorLiteralModule_basic",
    "TensorOpaqueLiteralModule_basic",
    "TensorToBoolZeroRank_basic",
    "TensorToFloatZeroRank_basic",
    "TensorToIntZeroRank_basic",
    "TensorsConcatModule_basic",
    "TensorsConcatNegativeDimModule_basic",
    "TensorsConcatNegativeDimStaticModule_basic",
    "TensorsConcatPromoteDTypeModule_basic",
    "TensorsConcatStaticModule_basic",
    "TestF16Return_basic",
    "TestMultipleTensorAndPrimitiveTypesReturn_basic",
    "TestMultipleTensorReturn_basic",
    "TileBigDimsSizeModule_basic",
    "TileSmallDimsSizeModule_basic",
    "ToCopyBoolDTypeStaticModule_basic",
    "ToDtypeBoolLayoutNoneStaticModule_basic",
    "ToDtypeLayoutCPUModule_basic",
    "ToDtypeLayoutNoneModule_basic",
    "ToDtypeLayoutStridedModule_basic",
    "TransposeIntModule_basic",
    "TransposeIntNegDimsModule_basic",
    "TriuBroadcastModule_basic",
    "TriuModule_basic",
    "TupleModule_basic",
    "TypeAsDifferentModule_basic",
    "TypeAsSameModule_basic",
    "TypeConversionF32ToF64Module_basic",
    "TypeConversionF64ToF32Module_basic",
    "TypeConversionI1ToF32Module_basic",
    "TypeConversionI1ToF64Module_basic",
    "TypeConversionI1ToI32Module_basic",
    "TypeConversionI1ToI64Module_basic",
    "TypeConversionI32ToI64Module_basic",
    "TypeConversionI64ToI32Module_basic",
    "UnbindIntGetItem_Module_basic",
    "UnbindIntListUnpack_Module_basic",
    "UnflattenIntNegativeOneDimStaticModule_basic",
    "UnflattenIntNegativeOneSizeStaticModule_basic",
    "UnflattenIntStaticModule_basic",
    "UnflattenStaticModule_basic",
    "UniformNoCorrelationModule_basic",
    "UniformStaticShapeModule_basic",
    "UnsafeView1DFoldModule_basic",
    "UnsafeViewCollapseModule_basic",
    "UnsafeViewDynamicExpandModule_basic",
    "UnsafeViewExpandModule_basic",
    "View1DFoldModule_basic",
    "ViewCollapseInferredDimModule_basic",
    "ViewCollapseModule_basic",
    "ViewCollapseOnesMiddleModule_basic",
    "ViewDynamicExpandCollapseModule_basic",
    "ViewDynamicExpandModule_basic",
    "ViewExpandCollapseModule_basic",
    "ViewExpandCollapseWithOnesModule_basic",
    "ViewExpandDynamicDimModule_basic",
    "ViewExpandInferredDimModule_basic",
    "ViewExpandModule_basic",
    "ViewExpandOnesBeforeAndAfterModule_basic",
    "ViewExpandOnesMiddleModule_basic",
    "ViewExpandOnesModule_basic",
    "ViewNegativeStaticModule_basic",
    "ViewNoChange1dModule_basic",
    "ViewNoChange2dModule_basic",
    "ViewNoChange3dModule_basic",
    "ViewNoChangeStaticModule_basic",
    "ViewOffsetBackwardTestStaticModule_basic",
    "ViewOffsetTestStaticModule_basic",
    "ViewTwoFiveThreeStaticModule_basic",
    "ViewTwoToThreeStaticModule_basic",
    "ZeroFloat32Module_basic",
    "ZeroInt32Module_basic",
    "ZeroInt64Module_basic",
    "ZerosLikeModule_defaultDtype",
    "ZerosLikeModule_falsePinMemory",
    "ZerosLikeModule_float",
    "ZerosLikeModule_int",
    "ZerosModuleDefaultDtype_basic",
    "ZerosModuleFalsePinMemory_basic",
    "ZerosModuleFloat2D_basic",
    "ZerosModuleFloat3D_basic",
    "ZerosModuleInt2D_basic",
    "ZerosModuleInt3D_basic",
}

STABLEHLO_CRASHING_SET =  {
    "AtenEmbeddingBagSumExample_basic",
}

# Write the TOSA set as a "passing" set as it is very early in development
# and very few tests work yet.
TOSA_PASS_SET = {
    "AdaptiveAvgPool2dNonUnitOutputSizeStaticModule_basic",
    "AdaptiveAvgPool2dUnitOutputSizeStaticModule_basic",
    "AddCDivModule_basic",
    "AddCDiv_Module_basic",
    "AddCMulModule_basic",
    "AddCMul_Module_basic",
    "Add_Module_basic",
    "AliasModule_basic",
    "ArangeDtypeFloatModule_basic",
    "ArangeIntModule_basic",
    "ArangeNegativeStartIntModule_basic",
    "ArangeStartIntModule_basic",
    "ArangeStartNegativeStepIntModule_basic",
    "ArangeStartOutModule_basic",
    "ArangeStartOutViewModule_basic",
    "ArangeStartStepIntModule_basic",
    "ArangeZeroElementOutputModule_basic",
    "ArangeDtypeIntModule_basic",
    "ArangeFalsePinMemoryModule_basic",
    "ArangeFloatModule_basic",
    "ArangeNegativeStartFloatModule_basic",
    "ArangeStartFloatModule_basic",
    "ArangeStartNegativeStepFloatModule_basic",
    "ArangeStartOutDtypeModule_basic",
    "ArangeStartStepFloatModule_basic",
    "ArgmaxModule_keepDim",
    "ArgmaxModule_with_dim",
    "AtenComplex64Module_basic",
    "AtenEyeMModuleCPUDevice_basic",
    "AtenEyeMModuleDefaultDtype_basic",
    "AtenEyeMModuleFalsePinMemory_basic",
    "AtenEyeMModuleFloat2D_basic",
    "AtenEyeModuleCPUDevice_basic",
    "AtenEyeModuleDefaultDtype_basic",
    "AtenEyeModuleFalsePinMemory_basic",
    "AtenEyeModuleFloat2D_basic",
    "AtenRoundIntModule_basic",
    "AtenInstanceNormModule_basic",
    "AtenToDeviceModule_basic",
    "BaddbmmBroadcast1DInputModule_basic",
    "BaddbmmBroadcast2DInputModule_basic",
    "BaddbmmDynamicModule_basic",
    "BaddbmmStaticModule_basic",
    "BaddbmmWithAlphaBetaModule_basic",
    "BaddbmmWithAlphaModule_basic",
    "BaddbmmWithBetaModule_basic",
    "BatchNorm1DModule_basic",
    "BatchNorm1DStaticShapeModule_basic",
    "BatchNorm1DWith2DInputModule_basic",
    "BatchNorm2DModule_basic",
    "BatchNorm3DModule_basic",
    "BmmFloatModule_basic",
    "BoolTensorHandleSignless_basic",
    "BoolTensorReturnFalseModule_basic",
    "BoolTensorReturnMixedModule_basic",
    "BoolTensorReturnTrueModule_basic",
    "BroadcastListConstructWithMinusOneModule_basic",
    "BroadcastToSameRankStaticModule_basic",
    "BroadcastZeroRankInputStaticModule_basic",
    "BucketizeTensorStaticFloatModule_basic",
    "BucketizeTensorStaticModule_basic",
    "CloneModule_basic",
    "ChunkListUnpackUneven_Module_basic",
    "ChunkListUnpack_Module_basic",
    "ConstantBoolParameterModule_basic",
    "ConstantPad2dStaticModule_basic",
    "ConstantPadNdModule_basic",
    "ConstantPadNdPartialStaticModule_basic",
    "ConstantPadNdStaticModule_basic",
    "ContiguousModule_basic",
    "Conv2dBiasNoPaddingModule_basic",
    "Conv2dNoPaddingModule_basic",
    "Conv2dWithPaddingDilationStrideModule_basic",
    "Conv2dWithPaddingDilationStrideStaticModule_basic",
    "Conv2dWithPaddingDilationStrideStaticModule_depthwise",
    "Conv2dWithPaddingDilationStrideStaticModule_depthwise_multiplier",
    "Conv2dWithPaddingModule_basic",
    "Convolution2DStaticModule_basic",
    "CosineSimilarityStaticModule_basic",
    "DetachModule_basic",
    "DropoutEvalFloatModule_basic",
    "DropoutEvalIntModule_basic",
    "DropoutModule_basic",
    "EinsumStaticContractRhsModule_basic",
    "EinsumStaticFourDimensionModule_basic",
    "EinsumStaticModule_basic",
    "ElementwiseAbsFloatModule_basic",
    "ElementwiseAbsIntModule_basic",
    "ElementwiseAddModule_basic",
    "ElementwiseAddScalarFloatModule_basic",
    "ElementwiseAddScalarInt64Module_basic",
    "ElementwiseAddScalarInt8Module_basic",
    "ElementwiseAddScalarIntModule_basic",
    "ElementwiseAddScalar_TensorLiteralInt32_Module_basic",
    "ElementwiseAtenDivIntScalarModule_basic",
    "ElementwiseAtenIsinfOpModule_basic",
    "ElementwiseAtenIsneginfOpModule_basic",
    "ElementwiseAtenIsposinfOpModule_basic",
    "ElementwiseAtenLogicalOrOpBrodcastModule_basic",
    "ElementwiseAtenLogicalOrOpDiffArgs1Module_basic",
    "ElementwiseAtenLogicalOrOpDiffArgs2Module_basic",
    "ElementwiseAtenLogicalOrOpDiffArgs3Module_basic",
    "ElementwiseAtenLogicalOrOpModule_basic",
    "ElementwiseAtenLogicalOrOpNegativeModule_basic",
    "ElementwiseAtenLogicalOrOpPromoteBroadcastStaticShapeModule_basic",
    "ElementwiseAtenLogicalOrOpRandomFloatModule_basic",
    "ElementwiseAtenLogicalOrOpRandomModule_basic",
    "ElementwiseAtenWhereSelfModule_basic",
    "ElementwiseBinaryModule_basic",
    "ElementwiseBinaryStaticShapeModule_basic",
    "ElementwiseBitwiseAndModule_basic",
    "ElementwiseBitwiseAndStaticShapeModule_basic",
    "ElementwiseBitwiseNotInt32Module_basic",
    "ElementwiseBitwiseNotInt64Module_basic",
    "ElementwiseBitwiseOrModule_basic",
    "ElementwiseBitwiseOrStaticShapeModule_basic",
    "ElementwiseBitwiseXorModule_basic",
    "ElementwiseBitwiseXorStaticShapeModule_basic",
    "ElementwiseCeilModule_basic",
    "ElementwiseClampMaxModule_basic",
    "ElementwiseClampMinModule_basic",
    "ElementwiseClampModule_basic",
    "ElementwiseClampTensorInt8Module_basic",
    "ElementwiseCloneChannelsLastMemoryFormatModule_basic",
    "ElementwiseCloneContiguousModule_basic",
    "ElementwiseCloneModule_basic",
    "ElementwiseDivScalarModule_basic",
    "ElementwiseDivTensorIntegerModule_basic",
    "ElementwiseDivTensorUnsignedIntegerModule_basic",
    "ElementwiseEluModule_basic",
    "ElementwiseEluNonDefaultModule_basic",
    "ElementwiseEqBoolScalarModule_basic",
    "ElementwiseEqDiffWidthScalarModule_basic",
    "ElementwiseEqFloatScalarModule_basic",
    "ElementwiseEqFloatTensorModule_basic",
    "ElementwiseEqIntScalarModule_basic",
    "ElementwiseEqIntTensorModule_basic",
    "ElementwiseExpModule_basic",
    "ElementwiseFlattenBroadcastModule_basic",
    "ElementwiseFloorIntModule_basic",
    "ElementwiseFloorModule_basic",
    "ElementwiseGeFloatIntScalarModule_basic",
    "ElementwiseGeFloatScalarModule_basic",
    "ElementwiseGeIntScalarModule_basic",
    "ElementwiseGeMixedIntScalarModule_basic",
    "ElementwiseGeluModule_basic",
    "ElementwiseGtFloatScalarModule_basic",
    "ElementwiseGtFloatTensorModule_basic",
    "ElementwiseGtIntScalarModule_basic",
    "ElementwiseGtIntTensorModule_basic",
    "ElementwiseGtMixed2ScalarModule_basic",
    "ElementwiseIsinfModule_basic",
    "ElementwiseAtenIsneginfOpModule_basic",
    "ElementwiseAtenIsposinfOpModule_basic",
    "ElementwiseIsnanModule_basic",
    "ElementwiseLeFloatTensorModule_basic",
    "ElementwiseLeIntTensorModule_basic",
    "ElementwiseLeakyReluModule_basic",
    "ElementwiseLeakyReluModule_basic",
    "ElementwiseLeakyReluStaticModule_basic",
    "ElementwiseLerpScalarIntModule_basic",
    "ElementwiseLerpScalarFloatModule_basic",
    "ElementwiseLog2Module_basic",
    "ElementwiseLogModule_basic",
    "ElementwiseLtDiffWidthScalarModule_basic",
    "ElementwiseLtFloatScalarModule_basic",
    "ElementwiseLtFloatTensorModule_basic",
    "ElementwiseLtIntScalarModule_basic",
    "ElementwiseLtIntTensorModule_basic",
    "ElementwiseMaxOtherIntModule_basic",
    "ElementwiseMaxOtherModule_basic",
    "ElementwiseMaximumIntModule_basic",
    "ElementwiseMaximumModule_basic",
    "ElementwiseMinOtherIntModule_basic",
    "ElementwiseMinOtherModule_basic",
    "ElementwiseMinimumIntModule_basic",
    "ElementwiseMinimumModule_basic",
    "ElementwiseMulScalarModule_basic",
    "ElementwiseMulScalarModule_float",
    "ElementwiseMulScalarModule_float",
    "ElementwiseMulScalarModule_int",
    "ElementwiseMulTensorIntModule_basic",
    "ElementwiseNeFloatScalarModule_basic",
    "ElementwiseNeFloatTensorModule_basic",
    "ElementwiseNeFloatTensorStaticModule_basic",
    "ElementwiseNeIntScalarModule_basic",
    "ElementwiseNeIntTensorModule_basic",
    "ElementwiseNeIntTensorStaticModule_basic",
    "ElementwiseNegModule_basic",
    "ElementwiseOrTensorModule_basic",
    "ElementwiseOrTensorStaticShapeModule_basic",
    "ElementwisePowModule_basic",
    "ElementwiseReciprocalModule_basic",
    "ElementwiseRelu6Module_basic",
    "ElementwiseReluModule_basic",
    "ElementwiseRemainderScalarModule_Float_basic",
    "ElementwiseRemainderScalarModule_Int_Float_basic",
    "ElementwiseRemainderScalarModule_Int_basic",
    "ElementwiseRemainderScalarModule_Int_basic",
    "ElementwiseRsqrtModule_basic",
    "ElementwiseSeluModule_basic",
    "ElementwiseSigmoidModule_basic",
    "ElementwiseSignModule_basic",
    "ElementwiseSqrtIntModule_basic",
    "ElementwiseSqrtModule_basic",
    "ElementwiseSubScalarFloatModule_basic",
    "ElementwiseSubScalarIntModule_basic",
    "ElementwiseSubTensorInt8Module_basic",
    "ElementwiseToDtypeIdentityModule_basic",
    "ElementwiseUnaryModule_basic",
    "ElementwiseUnsqueezeBroadcastModule_basic",
    "ElementwiseWhereScalarModule_basic",
    "ElementwiseNanToNumModule_Basic",
    "EmbeddingModule1DIndices_basic",
    "EmbeddingModuleI32Static_basic",
    "FlattenRank0Module_basic",
    "FlattenStaticModule_basic",
    "FullLikeModuleFloat3DStatic_basic",
    "FullLikeModuleInt2DStatic_basic",
    "FullModuleDefaultDtype_basic",
    "FullModuleFloat2D_basic",
    "FullModuleFloat3D_basic",
    "FullModuleInt3D_basic",
    "GatherStaticModule_basic",
    "GeluBackwardModule_basic",
    "GluStaticModule_basic",
    "HardTanhIntModule_basic",
    "HardTanhModule_basic",
    "HardsigmoidModule_basic",
    "HardsigmoidRandomModule_basic",
    "HardswishModule_basic",
    "HardswishRandomModule_basic",
    "HardtanhBackward_basic",
    "IndexPutImpl2DNoneIndexStaticModule_basic",
    "IndexTensorMultiIndexStaticModule_basic",
    "IndexTensorStaticModule_basic",
    "IscloseStaticModuleTrue_basic",
    "IscloseStaticModule_basic",
    "LayerNormNormalizeOverAllDimsModule_basic",
    "LeakyReluBackwardModule_basic",
    "LeakyReluBackwardStaticModule_basic",
    "LiftFreshCopyModule_basic",
    "LinalgVectorNormKeepDimModule_basic",
    "LinalgVectorNormModule_basic",
    "MaskedFillScalarDefaultModule_basic",
    "MaskedFillScalarIntValueModule_basic",
    "MaskedFillScalarIntValueStaticModule_basic",
    "MaskedFillTensorIntValueStaticModule_basic",
    "Matmul4dStatic_basic",
    "Matmul_3d",
    "Matmul_dot",
    "MatmulStaticBroadcast_basic",
    "MaxPool2dEmptyStrideStaticModule_basic",
    "MaxPool2dStaticCeilModeTrueModule_basic",
    "MaxPool2dStaticModule_basic",
    "MeanModule_basic",
    "MmDagModule_basic",
    "MoveDimIntModule_basic",
    "MoveDimIntModule_basic",
    "MoveDimIntNegativeIndexModule_basic",
    "MseLossNoReductionModule_basic",
    "NativeLayerNormModule4D_basic",
    "NewFullModuleDefaultDtype_basic",
    "NewFullModuleFalsePinMemory_basic",
    "NewFullModuleFloat2D_basic",
    "NewFullModuleFloat3DStatic_basic",
    "NewFullModuleFloat3D_basic",
    "NewFullModuleInt2DStatic_basic",
    "NewOnesModuleDefaultDtype_basic",
    "NewOnesModuleFalsePinMemory_basic",
    "NewOnesModuleFloat2D_basic",
    "NewOnesModuleFloat3D_basic",
    "NewOnesModuleInt2D_basic",
    "NewOnesModuleInt3D_basic",
    "NewZerosModuleDefaultDtype_basic",
    "NewZerosModuleFalsePinMemory_basic",
    "NewZerosModuleFloat2D_basic",
    "NewZerosModuleFloat3D_basic",
    "NewZerosModuleInt2D_basic",
    "NewZerosModuleInt3D_basic",
    "NewZerosStaticModuleLayoutStrided_basic",
    "NormalizeModule_basic",
    "NormScalarOptDimKeepDimModule_basic",
    "NormScalarOptDimModule_basic",
    "NumToTensorFloatModule_basic",
    "NumToTensorIntModule_basic",
    "NumpyTRank0Module_basic",
    "NumpyTRank1Module_basic",
    "NumpyTRank2Module_basic",
    "NumpyTRankNDynamicModule_basic",
    "NumpyTRankNStaticModule_basic",
    "OnesModuleCPUDevice_basic",
    "OnesModuleDefaultDtype_basic",
    "OnesModuleFalsePinMemory_basic",
    "OnesModuleFloat_basic",
    "OnesModuleInt_basic",
    "PadModule_basic",
    "PadWithNoneValModule_basic",
    "Permute0RankModule_basic",
    "PermuteModule_basic",
    "PermuteNegativeIndexModule_basic",
    "PrimsSqueezeEmptyDimensionsModule_basic",
    "PrimsSqueezeModule_basic",
    "PrimsViewOfModule_basic",
    "PrimsViewOfZeroRankModule_basic",
    "ReduceAmaxKeepDim_basic",
    "ReduceSumDimIntListFloatModule_basic",
    "ReduceSumDimIntListIntModule_basic",
    "ReduceSumDimIntListKeepDimFloatModule_basic",
    "ReduceSumDimIntListKeepDimIntModule_basic",
    "ReduceSumDimIntListKeepDimNegativeDimStaticModule_basic",
    "ReduceSumFloatModule_basic",
    "ReduceSumSignedIntModule_basic",
    "ReduceSumUnsignedIntModule_basic",
    "RepeatModule_basic",
    "ResNet18StaticModule_basic",
    "ReshapeAsModule_basic",
    "ReshapeCollapseModule_basic",
    "ReturnThreeTensorFloat32_basic",
    "ReturnTwoTensorF32I64_basic",
    "RsubFloatModule_basic",
    "RsubFloatModule_noalpha_basic",
    "RsubInt0d_NumToTensor_Module_basic",
    "ScalarTensorDefaultDtypeModule_basic",
    "ScalarTensorFloat32Module_basic",
    "ScalarTensorInt32Module_basic",
    "ScalarTensorInt64Module_basic",
    "SelectIntNegativeDimAndIndexStaticModule_basic",
    "SiluModule_basic",
    "SliceOutOfUpperBoundIndexStaticModule_basic",
    "SliceStaticModule_basic",
    "SoftmaxIntModule_basic",
    "SoftmaxIntNegDimModule_basic",
    "SplitTensorGetItem_Module_basic",
    "SplitTensorLastSmallerModule_basic",
    "SplitTensorListUnpackModule_basic",
    "SplitTensorNegativeDimModule_basic",
    "SplitWithSizesListUnpackModule_basic",
    "SquareModule_basic",
    "SqueezeDimModule_identity",
    "SqueezeDimModule_static",
    "SqueezeDimModule_unitDim",
    "SqueezeModule_allUnitDim",
    "SqueezeModule_broadcast",
    "SqueezeModule_noUnitDim",
    "SqueezeModule_static",
    "TModuleRank0_basic",
    "TModuleRank1_basic",
    "TModuleRank2_basic",
    "TanhBackward_basic",
    "TensorLiteralModule_basic",
    "TensorOpaqueLiteralModule_basic",
    "TensorsConcatNegativeDimStaticModule_basic",
    "TensorsConcatStaticModule_basic",
    "TestF16Return_basic",
    "TestMultipleTensorReturn_basic",
    "Threshold1dFloatModule_basic",
    "Threshold1dIntI32Module_basic",
    "Threshold2dFloatModule_basic",
    "Threshold3dFloatModule_basic",
    "TileBigDimsSizeModule_basic",
    "TileSmallDimsSizeModule_basic",
    "ToCopyBoolDTypeStaticModule_basic",
    "ToDtypeBoolLayoutNoneStaticModule_basic",
    "TransposeIntModule_basic",
    "TransposeIntNegDimsModule_basic",
    "TupleModule_basic",
    "TypeAsSameModule_basic",
    "TypePromotionAlphaWiderModule_basic",
    "TypePromotionDifferentCategoryModule_basic",
    "TypePromotionSameCategoryDifferentWidthModule_basic",
    "TypePromotionSameCategoryZeroRankWider_basic",
    "TypePromotionZeroRankHigherCategoryModule_basic",
    "UnbindIntGetItem_Module_basic",
    "UnbindIntListUnpack_Module_basic",
    "UnflattenIntNegativeOneDimStaticModule_basic",
    "UnflattenIntNegativeOneSizeStaticModule_basic",
    "UnflattenIntStaticModule_basic",
    "UnflattenStaticModule_basic",
    "UnsafeView1DFoldModule_basic",
    "UnsafeViewExpandModule_basic",
    "View1DFoldModule_basic",
    "ViewCollapseInferredDimModule_basic",
    "ViewCollapseOnesMiddleModule_basic",
    "ViewDoubleMergeStaticModule_basic",
    "ViewExpandCollapseModule_basic",
    "ViewExpandCollapseWithOnesModule_basic",
    "ViewExpandInferredDimModule_basic",
    "ViewExpandModule_basic",
    "ViewExpandOnesBeforeAndAfterModule_basic",
    "ViewExpandOnesMiddleModule_basic",
    "ViewExpandOnesMiddleOppModule_basic",
    "ViewExpandOnesModule_basic",
    "ViewFiveTestStaticModule_basic",
    "ViewNegativeStaticModule_basic",
    "ViewNoChangeStaticModule_basic",
    "ViewOffsetBackwardTestStaticModule_basic",
    "ViewOffsetTestStaticModule_basic",
    "ViewTwoFiveThreeStaticModule_basic",
    "ViewTwoToThreeStaticModule_basic",
    "ZerosModuleDefaultDtype_basic",
    "ZerosModuleFalsePinMemory_basic",
    "ZerosModuleFloat2D_basic",
    "ZerosModuleFloat3D_basic",
    "ZerosModuleInt2D_basic",
    "ZerosModuleInt3D_basic",
    "_LogSoftmaxModuleStable_basic",
    "_LogSoftmaxModule_basic",
    "_SoftmaxModule_basic",
}

MAKE_FX_TOSA_PASS_SET = (TOSA_PASS_SET | {
### Tests additionally passing in make_fx_tosa
    "AdaptiveAvgPool1dNonUnitOutputSizeStaticModule_basic",
    "AdaptiveAvgPool1dUnitOutputSizeStaticModule_basic",
    "AdaptiveAvgPool1dStaticEvenMultiple_basic",
    "CosineSimilarityModule_basic",
    "NativeGroupNormBackwardModule_basic",
    "ReduceFrobeniusNormKeepDimModule_basic",
    "ReduceFrobeniusNormModule_basic",
    "SliceWholeTensorModule_basic",
    "TensorFloatModule_basic",
    "TensorIntModule_basic",
    "AdaptiveAvgPool1dNonUnitOutputSizeStaticModule_basic",
    "AdaptiveAvgPool1dUnitOutputSizeStaticModule_basic",
}) - {
### Test failing in make_fx_tosa but not in tosa

    # Dynamic shape, has extra unsupported broadcast ops
    "Matmul_3d",
    "MatmulStaticBroadcast_basic",

    # failed to legalize operation 'torch.aten.max_pool2d_with_indices
    "MaxPool2dEmptyStrideStaticModule_basic",
    "MaxPool2dStaticCeilModeTrueModule_basic",
    "MaxPool2dStaticModule_basic",
    "ResNet18StaticModule_basic",

    # Unimplemented operator 'aten._index_put_impl_.hacked_twin'
    "IndexPutImpl1DFloatNonAccumulateModule_basic",
    "IndexPutImpl1DIntNonAccumulateModule_basic",
    # RuntimeError: The size of tensor a (7) must match the size of tensor b (3) at non-singleton dimension 1
    "Add_Module_basic",
    # failed to legalize operation 'torch.aten.to.dtype' that was explicitly marked illegal
    "AtenEyeModuleInt2D_basic",
    "AtenEyeMModuleInt2D_basic",

    "Conv2dBiasNoPaddingModule_basic",
    "Conv2dNoPaddingModule_basic",
    "Conv2dWithPaddingDilationStrideModule_basic",
    "Conv2dWithPaddingModule_basic",

    "AtenInstanceNormModule_basic",
}

LTC_CRASHING_SET = {
    # TODO: update test to move all inputs to the lazy device. Otherwise test fails with:
    # Check failed: lazy_tensor Input tensor is not a lazy tensor: CPUBoolType.
    "HBC_basic",
}

LTC_XFAIL_SET = {
    "CollapseAllDimensionsModule_basic",
    "CollapseRank1DynamicModule_basic",
    "CollapseStaticModule_basic",
    "CollapsePartialDynamicModule_basic",
    "CollapseFullDynamicModule_basic",
    "SplitDimStaticModule_basic",
    "SplitDimDynamicModule_basic",
    "PixelShuffleModuleStaticRank3Int64_basic",
    "PixelShuffleModuleStaticRank4Float32_basic",
    "PixelShuffleModuleFullDynamic_basic",
    "PixelShuffleModuleSpatiallyDynamic_basic",
    "PixelShuffleModuleSpatiallyStatic_basic",
    "ConvTbcModule_basic",
    "_Convolution2DAllFalseModule_basic",
    "_Convolution2DBenchmarkModule_basic",
    "_Convolution2DCudnnModule_basic",
    "_Convolution2DDeterministicModule_basic",
    "_Convolution2DTF32Module_basic",
    "_ConvolutionDeprecated2DAllFalseModule_basic",
    "_ConvolutionDeprecated2DBenchmarkModule_basic",
    "_ConvolutionDeprecated2DCudnnModule_basic",
    "_ConvolutionDeprecated2DDeterministicModule_basic",
    "MaxPool3dEmptyStrideStaticModule_basic",
    "AddIntModule_basic",
    "ArangeStartOutViewModule_basic",
    "AtenIntBoolOpModule_basic",
    "BernoulliTensorModule_basic",
    "BincountMinlengthModule_basic",
    "BincountModule_basic",
    "BincountStaticSizeModule_basic",
    "BoolFloatFalseModule_basic",
    "BoolFloatTrueModule_basic",
    "BoolIntFalseModule_basic",
    "BoolIntTrueModule_basic",
    "CeilFloatModule_basic",
    "DivFloatModule_basic",
    "EqIntModule_basic",
    "ExponentialModule_basic",
    "GeFloatIntModule_basic",
    "GeFloatModule_basic",
    "GeIntModule_basic",
    "GtFloatIntModule_basic",
    "GtIntModule_basic",
    "IndexPutImpl1DFloatAccumulateModule_basic",
    "IndexPutImpl1DFloatNonAccumulateModule_basic",
    "IndexPutImpl1DIntAccumulateModule_basic",
    "IndexPutImpl1DIntNonAccumulateModule_basic",
    "IndexPutImpl2DFloatAccumulateModule_basic",
    "IndexPutImpl2DFloatNonAccumulateModule_basic",
    "IndexPutImpl2DIndexModule_basic",
    "IndexPutImpl2DNoneIndexStaticModule_basic",
    "IndexPutImpl3DFloatAccumulateModule_basic",
    "IndexPutImpl3DFloatNonAccumulateModule_basic",
    "IndexPutImplIndexWithNoneModule_basic",
    "Matmul_dot",
    "MulIntModule_basic",
    "DivIntModule_basic",
    "NeFloatIntModule_basic",
    "NeIntModule_basic",
    "QuantizedMLP_basic",
    "ScalarImplicitFloatModule_basic",
    "ScalarImplicitIntModule_basic",
    "SliceEndSleStartModule_basic",
    "SliceOutOfUpperBoundIndexModule_basic",
    "SliceOutOfUpperBoundIndexStaticModule_basic",
    "SliceStartEqEndModule_basic",
    "SqrtIntModule_basic",
    "SubFloatModule_basic",
    "MulFloatModule_basic",
    "SubIntModule_basic",
    "TensorsStackPromoteDTypeModule_basic",
    "TensorToBoolZeroRank_basic",
    "TensorToBool_basic",
    "TensorToFloatZeroRank_basic",
    "TensorToFloat_basic",
    "TensorToIntZeroRank_basic",
    "TensorToInt_basic",
    "UniformModule_basic",
    "UnsafeViewCollapseDynamicWithAtenSizeIntModule_basic",
    "ViewCollapseDynamicWithAtenSizeIntModule_basic",
    "AtenEmbeddingBagSumExample_basic",
    "Aten_EmbeddingBagExample_basic",
    "ElementwiseLogitModule_basic",
    "ElementwiseRemainderScalarModule_Int_Float_basic",
    "ElementwiseRemainderScalarModule_Bool_basic",
    "ElementwiseLerpScalarIntModule_basic",
    "ElementwiseLerpScalarFloatModule_basic",
    "AtenIntTensorByteDtypeModule_basic",
    "AtenIntTensorCharDtypeModule_basic",
    "UpSampleNearest2dBackwardVec_basic",
    "UpSampleNearest2dBackwardOutputSizeNone_basic",
    "ConvolutionBackwardModule2D_basic",
    "ConvolutionBackwardModule2DPadded_basic",
    "VarMeanCorrectionModule_basic",
    "VarMeanCorrectionNoneModule_basic",
    "ElementwisePreluModule_basic",
    "VarMeanBiasedModule_basic",
    "VarMeanUnbiasedModule_basic",
    "RandnLikeModule_basic",
    "RandnLikeDtypeModule_basic",
    "NormalFunctionalModule_basic",
    "BernoulliFloatModule_basic",
    "BernoulliModule_basic",
    "BernoulliPModule_basic",
    "DropoutTrainModule_basic",
    "DropoutTrainStaticShapeModule_basic",
    "NativeDropoutTrainModule_basic",
    "NativeDropoutTrainStaticShapeModule_basic",
    "StdCorrectionKeepDimModule_basic",
    "StdCorrectionNoneModule_basic",
    "VarCorrectionKeepDimModule_basic",
    "VarCorrectionNoneModule_basic",
    "AtenFloatScalarModule_basic",
    "PrimsSqueezeModule_basic",
    "PrimsSqueezeEmptyDimensionsModule_basic",
    "PrimsViewOfModule_basic",
    "PrimsViewOfZeroRankModule_basic",
    "OneHotModule_basic",
    "VarMeanDimModule_basic",
    "VarMeanDimBiasedModule_basic",
    "AtenComplexImagModule_basic",
    "AtenComplexRealModule_basic",
    "AtenComplexViewModule_basic",
    "AtenRealView128Module_basic",
    "AtenRealView64Module_basic",
    "ScatterValueFloatModule_basic",
    "ScatterValueIntModule_basic",
    "UniformStaticShapeModule_basic",
    "AtenEmbeddingBagStaticModule_basic",
    "EmptyStridedModule_basic",
    "EmptyStridedSizeIntStrideModule_basic",
    "ElementwiseBitwiseAndScalarInt64Module_basic",
    "ElementwiseBitwiseAndScalarInt32Module_basic",
    "ElementwiseBitwiseAndScalarInt8Module_basic",
    "Conv2dQInt8Module_basic",
}

ONNX_XFAIL_SET = {
    # Failure - cast error
    "MeanDimNoneDimModule_basic",
    "MeanDtypeModule_basic",
    "MeanDynamicSizesModule_basic",
    "MeanModule_basic",
    "MseLossMeanReductionModule_basic",
    "PermuteNegativeIndexModule_basic",
    "StdBiasedModule_basic",
    "VarBiasedModule_basic",
    "VarMeanBiasedModule_basic",

    # Failure - constant int lowering
    "SplitTensorGetItem_Module_basic",
    "SplitTensorLastSmallerModule_basic",
    "SplitTensorListUnpackModule_basic",
    "SplitTensorNegativeDimModule_basic",
    "SplitWithSizesListUnpackModule_basic",
    "UnbindIntGetItem_Module_basic",
    "UnbindIntListUnpack_Module_basic",

    # Failure - incorrect numerics
    "AdaptiveAvgPool1dUnitOutputSizeDynamicModule_basic",
    "AdaptiveAvgPool2dUnitOutputSizeDynamicModule_basic",
    "ElementwiseAtan2TensorIntModule_basic",
    "ElementwiseLog10IntModule_basic",
    "ElementwiseLog2IntModule_basic",
    "ElementwiseSeluModule_basic",
    "FlipModuleStaticShape_basic",
    "FlipNegativeIndexModule_basic",
    "HardsigmoidModule_basic",
    "HardsigmoidRandomModule_basic",
    "IndexSelectDynamicInputSizeModule_basic",
    "IndexSelectWholeDimensionModule_basic",
    "IndexSelectWholeTensorModule_basic",
    "IndexTensorStaticModule_basic",
    "IndexTensorStaticNonContiguousWithNoneModule_basic",
    "PixelShuffleModuleStaticRank4Float32_basic",
    "ResNet18Module_basic",
    "SliceCopyEndGreaterThanDimSize_Module_basic",
    "SliceCopyNegative_Module_basic",
    "SliceCopyNonZeroDim_Module_basic",
    "SliceCopy_Module_basic",
    "TupleModule_basic",

    # Failure - incorrect shape
    "ArangeStartOutDtypeModule_basic",
    "ArangeStartOutViewModule_basic",
    "BroadcastDynamicDimModule_basic",
    "BroadcastToModule_basic",
    "ExpandModule_basic",
    "MoveDimIntNegativeIndexModule_basic",
    "ReduceAmaxKeepDim_basic",
    "ReduceMaxKeepDimReturnBoth_basic",
    "ReduceMaxNegativeDim_basic",
    "ViewSizeFromOtherTensor_basic",

    # Failure - onnx_export
    "AdaptiveAvgPool1dGeneralDynamic_basic",
    "AdaptiveAvgPool1dNonUnitOutputSizeDynamicModule_basic",
    "AdaptiveAvgPool1dStaticLargerOutput_basic",
    "AdaptiveAvgPool2dNonUnitOutputSizeDynamicModule_basic",
    "AdaptiveMaxPool2dDynamicWithIndices_basic",
    "AdaptiveMaxPool2dDynamic_basic",
    "AdaptiveMaxPool2dStaticWithIndices_basic",
    "AdaptiveMaxPool2dStatic_basic",
    "AddCDivModule_basic",
    "AddIntModule_basic",
    "Add_Module_basic",
    "AllBoolFalseModule_basic",
    "AllBoolTrueModule_basic",
    "AnyBoolFalseModule_basic",
    "AnyBoolTrueModule_basic",
    "AtenComplex64Module_basic",
    "AtenComplexImagModule_basic",
    "AtenComplexRealModule_basic",
    "AtenComplexViewModule_basic",
    "AtenEmbeddingBagStaticModule_basic",
    "AtenEmbeddingBagSumExample_basic",
    "AtenFloatScalarModule_basic",
    "AtenIntBoolOpConstFalseModule_basic",
    "AtenIntBoolOpConstTrueModule_basic",
    "AtenIntBoolOpModule_basic",
    "AtenIntTensorByteDtypeModule_basic",
    "AtenIntTensorCharDtypeModule_basic",
    "AtenItemFpOpModule_basic",
    "AtenItemIntOpModule_basic",
    "AtenMmQuint8_basic",
    "AtenRealView128Module_basic",
    "AtenRealView64Module_basic",
    "AtenSubFloatModule_basic",
    "AtenTopKModule_basic",
    "AtenTopKSmallestModule_basic",
    "Aten_EmbeddingBagExample_basic",
    "AvgPool2dWithoutPadModule_basic",
    "BatchMlpLayerModule_basic",
    "BincountMinlengthModule_basic",
    "BincountModule_basic",
    "BincountStaticSizeModule_basic",
    "BoolFloatConstantModule_basic",
    "BoolFloatFalseModule_basic",
    "BoolFloatTrueModule_basic",
    "BoolIntConstantModule_basic",
    "BoolIntFalseModule_basic",
    "BoolIntTrueModule_basic",
    "CeilFloatModule_basic",
    "ChunkListUnpackDynamic_Module_basic",
    "ChunkListUnpackUnevenDynamic_Module_basic",
    "CollapseAllDimensionsModule_basic",
    "CollapseFullDynamicModule_basic",
    "CollapsePartialDynamicModule_basic",
    "CollapseRank1DynamicModule_basic",
    "CollapseStaticModule_basic",
    "ConstantBoolParameterModule_basic",
    "ContainsIntList_False",
    "ContainsIntList_True",
    "Conv1dModule_basic",
    "Conv2dBiasNoPaddingModule_basic",
    "Conv2dModule_basic",
    "Conv2dNoPaddingModule_basic",
    "Conv2dQInt8Module_basic",
    "Conv2dWithPaddingDilationStrideModule_basic",
    "Conv2dWithPaddingModule_basic",
    "Conv3dModule_basic",
    "ConvTbcModule_basic",
    "Conv_Transpose2dModule_basic",
    "Convolution2DModule_basic",
    "Convolution2DStridedModule_basic",
    "ConvolutionBackwardModule2DPadded_basic",
    "ConvolutionBackwardModule2DStatic_basic",
    "ConvolutionBackwardModule2DStrided_basic",
    "ConvolutionBackwardModule2D_basic",
    "ConvolutionModule2DGroups_basic",
    "ConvolutionModule2DTransposeNonUnitOutputPadding_basic",
    "ConvolutionModule2DTransposeStrided_basic",
    "ConvolutionModule2DTranspose_basic",
    "DivFloatModule_basic",
    "DivIntModule_basic",
    "ElementwiseAcoshIntModule_basic",
    "ElementwiseAcoshModule_basic",
    "ElementwiseAsinhIntModule_basic",
    "ElementwiseAsinhModule_basic",
    "ElementwiseAtanhIntModule_basic",
    "ElementwiseAtanhModule_basic",
    "ElementwiseAtenIsneginfOpModule_basic",
    "ElementwiseAtenIsposinfOpModule_basic",
    "ElementwiseBitwiseAndModule_basic",
    "ElementwiseBitwiseAndScalarInt32Module_basic",
    "ElementwiseBitwiseAndScalarInt64Module_basic",
    "ElementwiseBitwiseAndScalarInt8Module_basic",
    "ElementwiseBitwiseAndStaticShapeModule_basic",
    "ElementwiseBitwiseLeftShiftInt32Module_basic",
    "ElementwiseBitwiseLeftShiftInt64Module_basic",
    "ElementwiseBitwiseLeftShiftInt8Module_basic",
    "ElementwiseBitwiseNotInt32Module_basic",
    "ElementwiseBitwiseNotInt64Module_basic",
    "ElementwiseBitwiseOrModule_basic",
    "ElementwiseBitwiseOrStaticShapeModule_basic",
    "ElementwiseBitwiseRightShiftInt32Module_basic",
    "ElementwiseBitwiseRightShiftInt64Module_basic",
    "ElementwiseBitwiseRightShiftInt8Module_basic",
    "ElementwiseBitwiseXorModule_basic",
    "ElementwiseBitwiseXorStaticShapeModule_basic",
    "ElementwiseCoshIntModule_basic",
    "ElementwiseCoshModule_basic",
    "ElementwiseDequantizePerChannelModule_basic",
    "ElementwiseDequantizePerTensorModule_basic",
    "ElementwiseEluNonDefaultModule_basic",
    "ElementwiseExpm1IntModule_basic",
    "ElementwiseExpm1Module_basic",
    "ElementwiseMulTensorComplexModule_basic",
    "ElementwiseOrTensorModule_basic",
    "ElementwiseOrTensorStaticShapeModule_basic",
    "ElementwiseQuantizePerTensorModule_basic",
    "ElementwiseRemainderTensorModule_Int_basic",
    "EmptyStridedModule_basic",
    "EmptyStridedSizeIntStrideModule_basic",
    "EqIntModule_basic",
    "ExponentialModule_basic",
    "FloatImplicitModule_basic",
    "GeFloatIntModule_basic",
    "GeFloatModule_basic",
    "GeIntModule_basic",
    "GeluBackwardModule_basic",
    "GtFloatIntModule_basic",
    "GtIntModule_basic",
    "HardtanhBackward_basic",
    "IndexPutImpl1DFloatAccumulateModule_basic",
    "IndexPutImpl1DFloatNonAccumulateModule_basic",
    "IndexPutImpl1DIntAccumulateModule_basic",
    "IndexPutImpl1DIntNonAccumulateModule_basic",
    "IndexPutImpl2DFloatAccumulateModule_basic",
    "IndexPutImpl2DFloatNonAccumulateModule_basic",
    "IndexPutImpl2DIndexModule_basic",
    "IndexPutImpl2DNoneIndexStaticModule_basic",
    "IndexPutImpl3DFloatAccumulateModule_basic",
    "IndexPutImpl3DFloatNonAccumulateModule_basic",
    "IndexPutImplIndexWithNoneModule_basic",
    "IntFloatModule_basic",
    "IntImplicitModule_basic",
    "IouOfModule_basic",
    "IsFloatingPointFloat_True",
    "IsFloatingPointInt_False",
    "IscloseStaticModuleTrue_basic",
    "IscloseStaticModule_basic",
    "LeakyReluBackwardModule_basic",
    "LeakyReluBackwardStaticModule_basic",
    "LenStrModule_basic",
    "LiftFreshCopyModule_basic",
    "LogSoftmaxBackwardModule_basic",
    "MaxPool2dCeilModeTrueModule_basic",
    "MaxPool2dModule_basic",
    "MaxPool2dWithIndicesAllOnesModule_basic",
    "MaxPool2dWithIndicesBackwardDynamic3DModule_basic",
    "MaxPool2dWithIndicesBackwardDynamic4DModule_basic",
    "MaxPool2dWithIndicesBackwardStatic3DModule_basic",
    "MaxPool2dWithIndicesBackwardStatic4DModule_basic",
    "MaxPool2dWithIndicesCeilModeTrueModule_basic",
    "MaxPool2dWithIndicesFullSizeKernelModule_basic",
    "MaxPool2dWithIndicesModule_basic",
    "MaxPool2dWithIndicesNonDefaultDilationModule_basic",
    "MaxPool2dWithIndicesNonDefaultParamsModule_basic",
    "MaxPool2dWithIndicesNonDefaultStrideModule_basic",
    "MaxPool3dCeilModeTrueModule_basic",
    "MaxPool3dLargeDatadModule_basic",
    "MaxPool3dModuleRandomSimple_basic",
    "MaxPool3dModule_basic",
    "MeanDimEmptyDimModule_basic",
    "Mlp1LayerModule_basic",
    "Mlp2LayerModuleNoBias_basic",
    "Mlp2LayerModule_basic",
    "MulFloatModule_basic",
    "MulIntModule_basic",
    "NarrowHorizontalTest2_basic",
    "NarrowHorizontalTest_basic",
    "NarrowTensorHorizontalModule_basic",
    "NarrowTensorVerticalModule_basic",
    "NarrowVerticalTest2_basic",
    "NarrowVerticalTest_basic",
    "NativeBatchNorm1DModule_basic",
    "NativeBatchNorm2DModule_basic",
    "NativeBatchNorm3DModule_basic",
    "NativeBatchNormNoneWeightModule_basic",
    "NativeDropoutEvalFloatModule_basic",
    "NativeGroupNormBackwardModule_basic",
    "NativeGroupNormModule_basic",
    "NativeLayerNormDynamicModule_basic",
    "NeFloatIntModule_basic",
    "NeIntModule_basic",
    "NewEmptyStridedModuleDefaultDtype_basic",
    "NllLossModuleBackward1DMeanWeight_basic",
    "NllLossModuleBackward1DMean_basic",
    "NllLossModuleBackward1DSumWeight_basic",
    "NllLossModuleBackward1DSum_basic",
    "NllLossModuleBackward1DWeight_basic",
    "NllLossModuleBackward1D_basic",
    "NllLossModuleBackwardMeanWeight_basic",
    "NllLossModuleBackwardMean_basic",
    "NllLossModuleBackwardSumWeight_basic",
    "NllLossModuleBackwardSum_basic",
    "NllLossModuleBackwardWeight_basic",
    "NllLossModuleBackward_basic",
    "NllLossModuleBackward_ignore_index",
    "NllLossModule_1D_basic",
    "NllLossModule_basic",
    "NllLossModule_ignore_index_out_of_bounds_basic",
    "NllLossModule_mean_basic",
    "NllLossModule_sum_basic",
    "NormScalarModule_basic",
    "NormScalarOptDimKeepDimModule_basic",
    "NormScalarOptDimModule_basic",
    "NormalFunctionalModule_basic",
    "NumToTensorFloatModule_basic",
    "NumToTensorIntModule_basic",
    "NumelModule_basic",
    "NumelZeroRankModule_basic",
    "PixelShuffleModuleFullDynamic_basic",
    "PixelShuffleModuleSpatiallyDynamic_basic",
    "PixelShuffleModuleSpatiallyStatic_basic",
    "PixelShuffleModuleStaticRank3Int64_basic",
    "PowIntFloatModule_basic",
    "PrimMaxIntModule_basic",
    "PrimMinIntDynamicModule_basic",
    "PrimMinIntModule_basic",
    "PrimsConvertElementTypeModule_basic",
    "PrimsSqueezeEmptyDimensionsModule_basic",
    "PrimsSqueezeModule_basic",
    "PrimsViewOfModule_basic",
    "PrimsViewOfZeroRankModule_basic",
    "RandIntDtypeModule_basic",
    "RandIntModule_basic",
    "RandIntPinMemoryModule_basic",
    "ReshapeAliasCollapseModule_basic",
    "ReshapeAliasExpandModule_basic",
    "ReshapeExpandModule_basic",
    "ScalarConstantTupleModule_basic",
    "ScalarImplicitFloatModule_basic",
    "ScalarImplicitIntModule_basic",
    "ScatterReduceFloatMaxModule",
    "ScatterReduceFloatMeanModule",
    "ScatterReduceFloatMeanModuleIncludeSelf",
    "ScatterReduceFloatMinModule",
    "ScatterReduceFloatProdModule",
    "ScatterReduceFloatSumModule",
    "ScatterReduceIntMaxModule",
    "ScatterReduceIntMeanModule",
    "ScatterReduceIntMeanModuleIncludeSelf",
    "ScatterReduceIntMinModule",
    "ScatterReduceIntProdModule",
    "ScatterReduceIntSumModule",
    "SelectScattertModule_basic",
    "SelectScattertStaticModule_basic",
    "SliceEndSleStartModule_basic",
    "SliceOutOfUpperBoundIndexModule_basic",
    "SliceScatterModule_basic",
    "SliceScatterNegativeDimModule_basic",
    "SliceScatterNegativeEndModule_basic",
    "SliceScatterStaticModule_basic",
    "SliceScatterStepVariationModule_basic",
    "SliceScatterZeroDimModule_basic",
    "SliceStartEqEndModule_basic",
    "SoftmaxBackwardModule_basic",
    "SortIntListReverse_basic",
    "SortIntList_basic",
    "SplitDimDynamicModule_basic",
    "SplitDimStaticModule_basic",
    "SqrtIntConstantModule_basic",
    "SqrtIntModule_basic",
    "StdCorrectionEmptyDimModule_basic",
    "StdDimEmptyDimModule_basic",
    "SubFloatModule_basic",
    "SubIntModule_basic",
    "TanhBackward_basic",
    "TensorToBoolZeroRank_basic",
    "TensorToBool_basic",
    "TensorToFloatZeroRank_basic",
    "TensorToFloat_basic",
    "TensorToIntZeroRank_basic",
    "TensorToInt_basic",
    "TestMultipleTensorAndPrimitiveTypesReturn_basic",
    "Threshold1dFloatModule_basic",
    "Threshold1dIntI32Module_basic",
    "Threshold1dIntModule_basic",
    "Threshold2dFloatModule_basic",
    "Threshold2dIntModule_basic",
    "Threshold3dFloatModule_basic",
    "Threshold3dIntModule_basic",
    "ThresholdBackward1dFloatModule_basic",
    "ThresholdBackward1dIntModule_basic",
    "ThresholdBackward1dMixedModule_basic",
    "ThresholdBackward2dFloatModule_basic",
    "ThresholdBackward2dIntModule_basic",
    "ThresholdBackward2dMixedModule_basic",
    "ThresholdBackward3dFloatModule_basic",
    "ThresholdBackward3dIntModule_basic",
    "ThresholdBackward3dMixedModule_basic",
    "ToCopyBoolDTypeStaticModule_basic",
    "ToCopyModule_basic",
    "ToCopyWithDTypeFalsePinMemoryModule_basic",
    "ToCopyWithDTypeModule_basic",
    "TorchPrimLoopForLikeModule_basic",
    "TorchPrimLoopWhileLikeModule_basic",
    "TraceModule_basic",
    "TraceModule_empty",
    "TraceModule_nonsquare",
    "TraceSignedIntModule_basic",
    "TraceUnsignedIntModule_basic",
    "TraceUnsignedIntModule_empty",
    "UniformModule_basic",
    "UniformNoCorrelationModule_basic",
    "UniformStaticShapeModule_basic",
    "UnsafeIndexPutHackedTwin1DFloatNonAccumulateModule_basic",
    "UnsafeView1DFoldModule_basic",
    "UnsafeViewCollapseDynamicWithAtenSizeIntModule_basic",
    "UnsafeViewCollapseModule_basic",
    "UnsafeViewDynamicExpandModule_basic",
    "UnsafeViewDynamicExpandWithAtenSizeIntModule_basic",
    "UnsafeViewExpandModule_basic",
    "UpSampleNearest2dBackwardScalesNone_basic",
    "UpSampleNearest2dBackward_basic",
    "UpSampleNearest2dDynamicFactor_basic",
    "UpSampleNearest2dStaticFactor_basic",
    "UpSampleNearest2d_basic",
    "VarCorrectionEmptyDimModule_basic",
    "VarDimEmptyDimModule_basic",
    "ViewCollapseDynamicWithAtenSizeIntModule_basic",
    "ViewCollapseModule_basic",
    "ViewDynamicExpandCollapseModule_basic",
    "ViewDynamicExpandCollapseWithAtenIntModule_basic",
    "ViewDynamicExpandModule_basic",
    "ViewDynamicExpandWithAtenSizeIntModule_basic",
    "ViewExpandDynamicDimModule_basic",
    "ViewNoChange1dModule_basic",
    "ViewNoChange2dModule_basic",
    "ViewNoChange3dModule_basic",
    "_Convolution2DAllFalseModule_basic",
    "_Convolution2DBenchmarkModule_basic",
    "_Convolution2DCudnnModule_basic",
    "_Convolution2DDeterministicModule_basic",
    "_Convolution2DTF32Module_basic",
    "_ConvolutionDeprecated2DAllFalseModule_basic",
    "_ConvolutionDeprecated2DBenchmarkModule_basic",
    "_ConvolutionDeprecated2DCudnnModule_basic",
    "_ConvolutionDeprecated2DDeterministicModule_basic",
    "_SoftmaxModule_basic",

    # Failure - onnx_import
    "DiagonalModule_basic",
    "DiagonalModule_nonsquare",
    "DiagonalModule_transposed",
    "DiagonalModule_with_dims",
    "DiagonalModule_with_dims_and_offset",
    "DiagonalModule_with_negative_dims",
    "DiagonalModule_with_offset",
    "ScatterReduceFloatMaxModuleIncludeSelf",
    "ScatterReduceFloatMinModuleIncludeSelf",
    "ScatterReduceFloatProdModuleIncludeSelf",
    "ScatterReduceFloatSumModuleIncludeSelf",
    "ScatterReduceIntMaxModuleIncludeSelf",
    "ScatterReduceIntMinModuleIncludeSelf",
    "ScatterReduceIntProdModuleIncludeSelf",
    "ScatterReduceIntSumModuleIncludeSelf",
    "TileBigDimsSizeModule_basic",
    "TileSmallDimsSizeModule_basic",

    # Failure - onnx_lowering: onnx.AveragePool
    "AdaptiveAvgPool1dNonUnitOutputSizeStaticModule_basic",
    "AdaptiveAvgPool1dStaticEvenMultiple_basic",
    "AdaptiveAvgPool2dNonUnitOutputSizeStaticModule_basic",
    "AvgPool1dFloatModule_basic",
    "AvgPool1dIntModule_basic",
    "AvgPool1dStaticModule_basic",
    "AvgPool2dCeilModeTrueModule_basic",
    "AvgPool2dDivisorOverrideModule_basic",
    "AvgPool2dFloatModule_basic",
    "AvgPool2dIntModule_basic",
    "AvgPool2dStaticModule_basic",

    # Failure - onnx_lowering: onnx.Cast
    "BucketizeTensorOutInt32RightModule_basic",
    "ElementwiseToDtypeI64ToI8Module_basic",
    "ElementwiseToDtypeI64ToUI8Module_basic",
    "HBC_basic",
    "QuantizedMLP_basic",
    "TypeConversionI1ToI32Module_basic",
    "TypeConversionI64ToI32Module_basic",

    # Failure - onnx_lowering: onnx.Clip
    "ElementwiseClampMaxModule_basic",
    "ElementwiseClampMinModule_basic",
    "ElementwiseClampMinTensorFloatModule_basic",
    "ElementwiseClampMinTensorIntModule_basic",
    "ElementwiseClampModule_basic",
    "ElementwiseClampTensorFloatModule_basic",
    "ElementwiseClampTensorInt8Module_basic",
    "ElementwiseClampTensorIntModule_basic",
    "NormalizeModule_basic",

    # Failure - onnx_lowering: onnx.Einsum
    "EinsumStaticContractRhsModule_basic",
    "EinsumStaticFourDimensionModule_basic",
    "EinsumStaticModule_basic",

    # Failure - onnx_lowering: onnx.Gemm
    "AtenMmFloatTypes_basic",
    "AtenMmIntTypes_basic",
    "MmDagModule_basic",
    "MmModule_basic",
    "MmModule_chained",
    "MmTanhModule_basic",

    # Failure - onnx_lowering: onnx.HardSwish
    "HardswishModule_basic",
    "HardswishRandomModule_basic",
    "MobilenetV3Module_basic",

    # Failure - onnx_lowering: onnx.LogSoftmax
    "LogSoftmaxIntModule_basic",
    "_LogSoftmaxModuleStable_basic",
    "_LogSoftmaxModule_basic",

    # Failure - onnx_lowering: onnx.MaxPool
    "MaxPool2dWithIndicesAllNegativeValuesModule_basic",
    "MaxPool2dWithIndicesNonDefaultPaddingModule_basic",
    "MaxPool2dWithIndicesStaticModule_basic",

    # Failure - onnx_lowering: onnx.Mod
    "ElementwiseRemainderScalarModule_Bool_basic",
    "ElementwiseRemainderScalarModule_Int_basic",
    "UnflattenIntNegativeOneDimStaticModule_basic",
    "UnflattenIntNegativeOneSizeStaticModule_basic",
    "UnflattenIntStaticModule_basic",
    "UnflattenStaticModule_basic",

    # Failure - onnx_lowering: onnx.OneHot
    "OneHotModule_basic",

    # Failure - onnx_lowering: onnx.Pad
    "ConstantPad2dStaticModule_basic",
    "ConstantPadNdModule_basic",
    "ConstantPadNdPartialStaticModule_basic",
    "ConstantPadNdStaticModule_basic",
    "PadModule_basic",
    "PadWithNoneValModule_basic",
    "ReflectionPad1dModule2dInput_Right",
    "ReflectionPad1dModule2dInput_basic",
    "ReflectionPad1dModule3dInput_Left",
    "ReflectionPad1dModule3dInput_basic",
    "ReflectionPad2dModule_Bottom",
    "ReflectionPad2dModule_Left",
    "ReflectionPad2dModule_Right",
    "ReflectionPad2dModule_Top",
    "ReflectionPad2dModule_basic",
    "ReplicationPad2dModule_basic",
    "ReplicationPad2dModule_bottom0",
    "ReplicationPad2dModule_left0",
    "ReplicationPad2dModule_right0",
    "ReplicationPad2dModule_top0",

    # Failure - onnx_lowering: onnx.RandomNormal
    "RandnDtypeDeviceModule_basic",
    "RandnGeneratorF64Module_basic",
    "RandnGeneratorModule_basic",
    "RandnModule_basic",

    # Failure - onnx_lowering: onnx.RandomNormalLike
    "RandnLikeDtypeModule_basic",
    "RandnLikeModule_basic",

    # Failure - onnx_lowering: onnx.RandomUniform
    "RandIntLowDtypeModule_basic",
    "RandIntLowModule_basic",

    # Failure - onnx_lowering: onnx.RandomUniformLike
    "BernoulliFloatModule_basic",
    "BernoulliPModule_basic",
    "BernoulliTensorModule_basic",
    "RandLikeDtypeModule_basic",
    "RandLikeModule_basic",
    "RandModule_basic",

    # Failure - onnx_lowering: onnx.ReduceL1
    "ReduceL1NormModule_basic",
    "ReduceL1NormWithDTypeModule_basic",

    # Failure - onnx_lowering: onnx.ReduceL2
    "ReduceL2NormModule_basic",

    # Failure - onnx_lowering: onnx.ReduceProd
    "BernoulliModule_basic",
    "DropoutTrainModule_basic",
    "DropoutTrainStaticShapeModule_basic",
    "NativeDropoutTrainModule_basic",
    "NativeDropoutTrainStaticShapeModule_basic",
    "ReduceProdDimIntFloatModule_basic",
    "StdCorrectionAllDimReduceModule_basic",
    "StdCorrectionKeepDimModule_basic",
    "StdCorrectionLargeInputModule_basic",
    "StdCorrectionModule_basic",
    "StdCorrectionNoneModule_basic",
    "StdCorrectionSingleDimReduceModule_basic",
    "StdDimKeepDimFalseModule_basic",
    "StdDimKeepDimTrueModule_basic",
    "StdDimNoneDimModule_basic",
    "StdUnbiasedModule_basic",
    "VarCorrectionAllDimReduceModule_basic",
    "VarCorrectionKeepDimModule_basic",
    "VarCorrectionLargeInputModule_basic",
    "VarCorrectionModule_basic",
    "VarCorrectionNoneModule_basic",
    "VarCorrectionSingleDimReduceModule_basic",
    "VarDimAllDimReduceModule_basic",
    "VarDimModule_basic",
    "VarDimMultiDimModule_basic",
    "VarDimNegativeModule_basic",
    "VarDimNoneDimModule_basic",
    "VarDimSingleDimModule_basic",
    "VarDimUnbiasedModule_basic",
    "VarMeanCorrectionModule_basic",
    "VarMeanCorrectionNoneModule_basic",
    "VarMeanDimModule_basic",
    "VarMeanUnbiasedModule_basic",
    "VarUnbiasedModule_basic",

    # Failure - onnx_lowering: onnx.ReduceSum
    "MseLossSumReductionWithDifferentElemTypeModule_basic",
    "ReduceL3NormAllDimsModule_basic",
    "ReduceL3NormKeepDimModule_basic",
    "ReduceSumDtypeFloatModule_basic",
    "ReduceSumDtypeIntModule_basic",
    "ReduceSumElementTypeBoolModule_basic",
    "ReduceSumFloatModule_basic",
    "ReduceSumSignedIntModule_basic",
    "ReduceSumUnsignedIntModule_basic",

    # Failure - onnx_lowering: onnx.Resize
    "UpSampleNearest2dDynamicSize_basic",
    "UpSampleNearest2dStaticSize_basic",

    # Failure - onnx_lowering: onnx.ScatterElements
    "ScatterSrcModule_basic",
    "ScatterSrcStaticModule_basic",
    "ScatterValueFloatModule_basic",
    "ScatterValueIntModule_basic",

    # Failure - onnx_lowering: onnx.ScatterND
    "IndexPut1DFloatAccumulateModule_basic",
    "IndexPut1DFloatNonAccumulateModule_basic",
    "IndexPut1DIntAccumulateModule_basic",
    "IndexPut1DIntNonAccumulateModule_basic",
    "IndexPut2DFloatAccumulateModule_basic",
    "IndexPut2DFloatNonAccumulateModule_basic",
    "IndexPut2DIntAccumulateModule_basic",
    "IndexPut2DIntNonAccumulateModule_basic",
    "IndexPut3DFloatAccumulateModule_basic",
    "IndexPut3DFloatNonAccumulateModule_basic",
    "IndexPut3DIntAccumulateModule_basic",
    "IndexPut3DIntNonAccumulateModule_basic",
    "IndexPutHackedTwin1DFloatAccumulateModule_basic",
    "IndexPutHackedTwin1DFloatNonAccumulateModule_basic",
    "IndexPutHackedTwin1DIntAccumulateModule_basic",
    "IndexPutHackedTwin1DIntNonAccumulateModule_basic",
    "IndexPutHackedTwin2DFloatAccumulateModule_basic",
    "IndexPutHackedTwin2DFloatNonAccumulateModule_basic",
    "IndexPutHackedTwin2DIntAccumulateModule_basic",
    "IndexPutHackedTwin2DIntNonAccumulateModule_basic",
    "IndexPutHackedTwin3DFloatAccumulateModule_basic",
    "IndexPutHackedTwin3DFloatNonAccumulateModule_basic",
    "IndexPutHackedTwin3DIntAccumulateModule_basic",
    "IndexPutHackedTwin3DIntNonAccumulateModule_basic",

    # Failure - onnx_lowering: onnx.SoftmaxCrossEntropyLoss
    "CrossEntropyLossModule_basic",
    "CrossEntropyLossNoReductionModule_basic",

    # Failure - onnx_lowering: onnx.Softplus
    "ElementwiseMishModule_basic",
    "SoftplusModule_basic",

    # Failure - onnx_lowering: onnx.Squeeze
    "SqueezeModule_allUnitDim",
    "SqueezeModule_broadcast",
    "SqueezeModule_static",

    # Failure - onnx_lowering: onnx.TopK
    "SortTensorDescending_basic",
    "SortTensorInteger_basic",
    "SortTensorNegativeDimension_basic",
    "SortTensorSpecificDimension_basic",
    "SortTensor_basic",

    # Failure - onnx_lowering: onnx.Trilu
    "AtenTrilModule_basic",
    "AtenTrilWithNegDiagonalModule_basic",
    "AtenTrilWithPosDiagonalModule_basic",
    "AtenTriuModule_basic",
    "AtenTriuWithNegDiagonalModule_basic",
    "AtenTriuWithPosDiagonalModule_basic",
    "TriuBroadcastModule_basic",
    "TriuModule_basic",

    # Failure - rankless return
    "ReduceAmaxMultiDim_basic",
    "ReduceAmaxOutOfOrderDim_basic",
    "ReduceAmaxSingleDim_basic",
    "ReduceMaxAllDims_basic",
    "ReduceMaxAlongDimNegative_basic",
    "ReduceMaxAlongDimSignedInt_basic",
    "ReduceMaxAlongDimUnsignedInt_basic",
    "ReduceMaxAlongDim_basic",
    "ReduceMaxFloatModule_basic",
    "ReduceMaxSignedIntModule_basic",
    "ReduceMaxUnsignedIntModule_basic",

    # Failure - torch.aten.view lower
    "AddSizeIntModule_basic",
    "ElementwiseFlattenBroadcastModule_basic",
    "IndexTensorDyanmicInputContiguousWithNoneModule_basic",
    "IndexTensorDyanmicInputNonContiguousWithNoneModule_basic",
    "IndexTensorHackedTwinMultiInputNonContiguousMultipleStaticDims_basic",
    "IndexTensorMultiInputContiguousCenter_basic",
    "IndexTensorMultiInputNonContiguousMultipleStaticDims_basic",
    "IndexTensorMultiInputNonContiguous_basic",
    "IndexTensorMultiInputOneDim_basic",
    "IndexTensorMultiInputThreeIndexers_basic",
    "IndexTensorMultiInput_basic",
    "IndexTensorStaticContiguousWithNoneModule_basic",
    "RepeatModule_basic",
    "SelectIntModule_basic",
    "SliceSingleIdxModule_basic",
    "ViewFlattenAndExpandModule_basic",
    "ViewSizeDimFollowedByCollapsedOnesModule_basic",
    "ViewSizeDimFollowedByExpandedOnesModule_basic",
    "ViewSizeDimLedAndFollowedByCollapsedOnesModule_basic",
    "ViewSizeDimLedAndFollowedByExpandedOnesModule_basic",
    "ViewSizeDimLedByCollapsedOnesModule_basic",
    "ViewSizeDimLedByExpandedOnesModule_basic",

    # Failure - unknown
    "BucketizeTensorFloatModule_basic",
    "BucketizeTensorModule_basic",
    "BucketizeTensorStaticFloatModule_basic",
    "BucketizeTensorStaticModule_basic",
    "Conv2dWithPaddingDilationStrideStaticModule_depthwise_multiplier",
    "CopyWithDifferentDTypesAndSizesModule_basic",
    "CopyWithDifferentDTypesModule_basic",
    "CosineSimilarityStaticBroadcastModule_basic",
    "CumsumInputDtypeInt32Module_basic",
    "ElementwiseAcosIntModule_basic",
    "ElementwiseAsinIntModule_basic",
    "ElementwiseAtanTensorIntModule_basic",
    "ElementwiseCosIntModule_basic",
    "ElementwiseDivRoundingModeTruncModule_basic",
    "ElementwiseErfIntModule_basic",
    "ElementwiseExpIntModule_basic",
    "ElementwiseLogIntModule_basic",
    "ElementwisePreluModule_basic",
    "ElementwiseSigmoidIntModule_basic",
    "ElementwiseSinIntModule_basic",
    "ElementwiseTanIntModule_basic",
    "ElementwiseUnaryIntModule_basic",
    "ElementwiseUnsqueezeNegDimsModule_basic",
    "ElementwiseWhereScalarModule_basic",
    "EmbeddingModule1DIndices_basic",
    "EmbeddingModuleF16_basic",
    "EmbeddingModuleI32_basic",
    "EmbeddingModuleI64_basic",
    "FlattenDynamicModule_basic",
    "GluStaticModule_basic",
    "GroupNormModule_basic",
    "IndexSelectDynamicIndexSizeModule_basic",
    "IndexSelectDynamicModulebasic",
    "IndexTensorHackedTwinModule3dInput_basic",
    "IndexTensorHackedTwinModule_basic",
    "IndexTensorModule3dInput_basic",
    "IndexTensorModule_basic",
    "IndexTensorMultiInputContiguousOneDimDynamic_basic",
    "IndexTensorMultiInputNonContiguousDynamic_basic",
    "IndexTensorMultiInputNonContiguousOneDimDynamic_basic",
    "IndexTensorSelectDimModule_basic",
    "MaskedFillTensorFloatValueModule_basic",
    "ReduceAllDimEmpty_basic",
    "ReduceAllDimFloat_basic",
    "ReduceAllDimInt_basic",
    "ReduceMinAlongDimUnsignedInt_basic",
    "TensorsStackNegativeDimModule_basic",
    "TensorsStackPromoteDTypeModule_basic",
}

ONNX_CRASHING_SET = { }

