"""
A collection of file utilities for replicating the directory structure created by CMake.
"""

def _copy_into_directory_impl(ctx):
    outputs = []

    # for each source, we want to expand its files.
    for src, target_dir in ctx.attr.srcs.items():
        files = src[DefaultInfo].files

        # symlink the files over to the target directory
        for file in files.to_list():
            target_file = target_dir + "/" + file.basename
            new_file = ctx.actions.declare_file(target_file)
            ctx.actions.symlink(
                output = new_file,
                target_file = file,
            )
            outputs.append(new_file)
    return [
        DefaultInfo(files = depset(outputs)),
    ]

copy_into_directory = rule(
    implementation = _copy_into_directory_impl,
    doc = """Makes the files generated by the labels (keys) available at the subdirectory specified by the values.

    For example, in order to copy the files under "@llvm-project//mlir/python:IRPyFiles" to "torch_mlir/", you would write:
    copy_into_directory(
        name = "...",
        srcs = {
            "@llvm-project//mlir/python:IRPyFiles": "torch_mlir",
        }
    )

    Currently as an implementation detail, this rule uses symlinks as they are natively supported by the ctx object. This may change in the future.
    """,
    attrs = {
        "srcs": attr.label_keyed_string_dict(allow_files = True, mandatory = True, doc = "A mapping from labels to their subdirectory targets."),
    },
)
