name: Lint Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  static_lint_checks:
    name: Static Lint Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate GitHub Actions yaml files
        run: |
          yamllint ./.github/workflows/ ./.github/actions/
