name: RollPyTorch Merge

on:
  workflow_run:
    workflows: [Build and Test]
    types: [completed]
    branches: [rollpytorch]

jobs:
  merge-pr:
    runs-on: ubuntu-latest
    if: |
      github.repository == 'llvm/torch-mlir' &&
      github.event.workflow_run.actor.login == 'silvasean' &&
      github.event.workflow_run.conclusion == 'success'

    steps:
    - name: Merge RollPyTorch PR
      run: |
        for pr_id in ${{ join(github.event.workflow_run.pull_requests.*.number, ' ') }}
        do
          echo "Merging PR: $pr_id"
          gh pr merge $pr_id --delete-branch --squash
        done
      shell: bash
      env:
        GH_TOKEN: ${{ secrets.ROLLPYTORCH_TOKEN1 }}
